- website/process_notebooks.py
- website/talks/2024-11-11/index.mdx
- website/talks/2024-11-12/index.mdx
- website/talks/2024-11-18/index.mdx
- website/talks/future_talks/index.mdx
clean up codes & update community talks
> clean up codes & update community talks 

- autogen/version.py
> bump version

- notebook/agentchat_swarm_w_groupchat_legacy.ipynb
- website/blog/2024-11-17-Swarm/index.mdx
- Update blogpost
- fix error: legacy swarm should have title in the first line to be compiled in the website.
> Update Swarm Blog Post

- setup.py
Need to add pandas to setup.py
> CaptainAgent install fix: Update setup

- notebook/agentchat_captainagent.ipynb
- website/docs/topics/captainagent/configurations.mdx
Update instructions on setting backbone for CaptainAgent.
> Update docs and notebook

- website/blog/2024-11-15-CaptainAgent/index.mdx
> fix broken link

- MAINTAINERS.md
> add Rudy(myself, github: rudyalways) to maintainer

- README.md
- website/docs/contributor-guide/contributing.md
This PR resolves an item in https://github.com/ag2ai/ag2/issues/40
> Add link to roadmap issues

- MAINTAINERS.md
> added HaiyangLi to maintainer

- MAINTAINERS.md
> Update MAINTAINERS.md to add Eric Moore (SomeComputerGuy)

- website/docusaurus.config.js
- website/src/components/GalleryPage.js
- website/talks/2024-11-25/index.mdx
- website/talks/2024-11-28/index.mdx
- website/talks/future_talks/index.mdx
1. update talks
2. config to render all previous talks
3. try to fix gallery images
> Update talks & try to fix gallery 

- .github/workflows/python-package.yml
- autogen/version.py
- setup_ag2.py
- setup_autogen.py
> Package description udpate

- MAINTAINERS.md
> Update MAINTAINERS.md - Add Tvrtko Sternak to maintainers

- website/blog/2024-11-27-Prompt-Leakage-Probing/img/probing_flow.png
- website/blog/2024-11-27-Prompt-Leakage-Probing/img/prompt_leakage_report.png
- website/blog/2024-11-27-Prompt-Leakage-Probing/img/prompt_leakage_social_img.png
- website/blog/2024-11-27-Prompt-Leakage-Probing/img/prompt_test_chat.png
- website/blog/2024-11-27-Prompt-Leakage-Probing/index.mdx
- website/blog/authors.yml
This PR adds a new blog post titled "Testing for Prompt Leakage Security Using Autogen". The post provides an overview of the framework for detecting prompt leakage vulnerabilities in LLMs, outlines its key components, and demonstrates its capabilities. It aims to inform and engage the community by showcasing the practical application of the framework.
> [BLOG] Write Prompt Leakage Probing blogpost

- website/docs/tutorial/code-executors.ipynb
> Fix minor grammatical issue in documentation.

- .github/workflows/python-package.yml
- autogen/version.py
> Package test and version bump

- autogen/version.py
- notebook/agentchat_graph_rag_falkordb.ipynb
Bump version 0.5.1 for release.
> Bump version to 0.5.1

- autogen/version.py
Version bump 0.5.2 (tested pip installs with 0.5.2b1 and extras work)
> Bump to version 0.5.2

- MAINTAINERS.md
> Update MAINTAINERS.md | Add myself to contributors

- autogen/tools/tool.py
- notebook/tools_from_crewai_tool.ipynb
Fix Tools class and add initial tutorial
> Add tool imports upstream

- autogen/version.py
0.5.3b1 pre-release pip install passed. Version > 0.5.3
N/A
> Update version.py to 0.5.3

- website/src/data/gallery.json
I have added a project in the project gallery of autogen to showcase a project I built using Autogen framework.
> Added a project in gallery.json

- setup.py
Openai version should be upgraded to >= 1.57 to include latest httpx bug fixes
Closes #185
> Upgrade openai version to >=1.57

- test/agentchat/contrib/agent_eval/test_agent_eval.py
- test/agentchat/contrib/capabilities/chat_with_teachable_agent.py
- test/agentchat/contrib/capabilities/test_image_generation_capability.py
- test/agentchat/contrib/capabilities/test_teachable_agent.py
- test/agentchat/contrib/capabilities/test_transform_messages.py
- test/agentchat/contrib/test_agent_builder.py
- test/agentchat/contrib/test_gpt_assistant.py
- test/agentchat/contrib/test_llamaindex_conversable_agent.py
- test/agentchat/contrib/test_reasoning_agent.py
- test/agentchat/test_agent_logging.py
- test/agentchat/test_agent_usage.py
- test/agentchat/test_assistant_agent.py
- test/agentchat/test_async_chats.py
- test/agentchat/test_async_get_human_input.py
- test/agentchat/test_cache_agent.py
- test/agentchat/test_chats.py
- test/agentchat/test_conversable_agent.py
- test/agentchat/test_function_call.py
- test/agentchat/test_function_call_groupchat.py
- test/agentchat/test_human_input.py
- test/agentchat/test_math_user_proxy_agent.py
- test/agentchat/test_nested.py
- test/agentchat/test_tool_calls.py
- test/io/test_websockets.py
- test/oai/_test_completion.py
- test/test_code_utils.py
- test/test_logging.py
- test/test_token_count.py
A lot of the current tests are using GPT-4 or GPT-3.5-Turbo. These have been superseded by GPT-4o and GPT-4o-mini, which will be more commonly used by users.
This update changes them to the newer versions in the tests, as well as various other places. Additionally, the Azure version has moved along from 2024-02-01 to 2024-08-06, so this updates that as well.
Files will be added progressively to check for issues.
N/A
> Update of OpenAI (and Azure) models and versions

- website/docs/topics/swarm.ipynb
corrects a small typo in https://ag2ai.github.io/ag2/docs/topics/swarm/ ?
> small typo in swarm doc

- setup.py
- test/test_browser_utils.py
> [Chore] Pytest upgraded to version 8

- autogen/agentchat/realtime_agent/client.py
- autogen/agentchat/realtime_agent/realtime_agent.py
- notebook/agentchat_realtime_swarm.ipynb
- notebook/agentchat_realtime_tool.ipynb
> Realtime agent refactoring anyio

- website/mint.json
> Update blog posts navigation

- autogen/version.py
> Bump version 0.6.0b2

- website/blog/2024-12-20-Tools-interoperability/index.mdx
> Replace placeholder video with tools interoperability one

- website/mint.json
> Remove duplicate entry from navigation

- autogen/version.py
> version bump

- website/blog/2024-12-20-Reasoning-Update/img/mcts_example.png
- website/blog/2024-12-20-Reasoning-Update/index.mdx
> Update mcts blog image

- autogen/oai/gemini.py
This PR will be used to fix Google Gemini client class bugs. If anyone has any, let's work on them here.
N/A
> Google Gemini Client fixes

- .github/workflows/deploy-website.yml
> Set up redirects from gh-pages to new domain

- =8
> remove unnecessary log file from main

- website/blog/2024-12-06-FalkorDB-Structured/index.mdx
- website/mint.json
> Add youtube video to 2024-12-06-FalkorDB-Structured blog

- notebook/agentchat_function_call_currency_calculator.ipynb
> Fix failing notebook test

- autogen/tools/tool.py
- test/tools/test_tool.py
> Add __call__ method to Tool

- website/docs/ecosystem/promptflow.mdx
> [Docs] Update links

- website/mint.json
- website/snippets/data/NotebooksMetadata.mdx
> Add new Realtime notebook with websocket API

- website/blog/2024-12-20-RealtimeAgent/index.mdx
- website/docs/contributor-guide/contributing.mdx
> Fix broken links

- notebook/agentchat_realtime_websocket.ipynb
> [RealtimeAgent Notebook] Fix dependencies and imports

- autogen/agentchat/conversable_agent.py
- autogen/agentchat/realtime_agent/function_observer.py
- autogen/agentchat/realtime_agent/realtime_agent.py
- autogen/agentchat/realtime_agent/websocket_audio_adapter.py
- autogen/interop/crewai/crewai.py
- autogen/interop/langchain/langchain.py
- autogen/interop/pydantic_ai/pydantic_ai_tool.py
- autogen/tools/tool.py
- notebook/agentchat_realtime_websocket.ipynb
- test/agentchat/realtime_agent/conftest.py
- test/agentchat/realtime_agent/realtime_test_utils.py
- test/agentchat/realtime_agent/test_e2e.py
- test/agentchat/realtime_agent/test_oai_realtime_client.py
- test/agentchat/test_conversable_agent.py
- test/tools/test_tool.py
> Refactoring of dependancy injection, tools and realtime client

- autogen/messages/agent_messages.py
> Bug fix: Extract values from dict instead of copying dict in PostCaryoverProcessing

- website/talks/2024-12-12/index.mdx
- website/talks/2024-12-19/index.mdx
- website/talks/future_talks/index.mdx
1. update previous community talks. 
2. add lu.ma link
> community talks

- autogen/agentchat/contrib/reasoning_agent.py
future enhancements and for the ag2arena (simple-bench)
> add method property to ReasoningAgent

- notebook/config_loader_utility_functions.ipynb
- website/blog/2024-12-20-RealtimeAgent/index.mdx
- website/mint.json
- website/talks/2024-12-12/index.mdx
- website/talks/2024-12-19/index.mdx
The documentation build process was failing due to recent errors, which blocked the deployment of updated documentation. This PR addresses both the build issues and the broken links found, ensuring the documentation deployment pipeline works as expected.
Closes #359
> [Docs] Fix Build Errors and Broken Links in Documentation

- autogen/agentchat/conversable_agent.py
- autogen/io/base.py
- autogen/io/console.py
- autogen/io/websockets.py
- autogen/messages/agent_messages.py
- autogen/messages/base_message.py
- test/io/test_base.py
- test/io/test_websockets.py
- test/messages/test_agent_messages.py
> Merge changes to dedicated branch

- notebook/config_loader_utility_functions.ipynb
> [Docs] Fix broken link

- setup.py
- test/interop/langchain/test_langchain.py
Fixing failing CI test:
https://github.com/ag2ai/ag2/actions/runs/12640016948/job/35219542932?pr=366
> Fix failing CI test in interop-langchain submodule

- .muffet-excluded-links.txt
> [Docs] Fix URL in muffet exclusion list

- autogen/messages/base_message.py
- autogen/messages/client_messages.py
- autogen/oai/client.py
- test/messages/test_base_message.py
- test/messages/test_client_messages.py
> Fix wrap message to accept message model with single content parameter

- website/blog/2024-12-20-Reasoning-Update/img/mcts_example.png
This PR updates the image in the ["Reasoning Update" blog post](https://docs.ag2.ai/blog/2024-12-20-Reasoning-Update/index) to ensure proper visibility in the light theme. Changes include:
Replacing the existing image with an updated version optimized for both light and dark themes.
Closes #384
> [Docs] Fix Image in "ReasoningAgent Update" Blog Post

- autogen/version.py
Version 0.7.0b1 pre-releaese
N/A
> Bump version to 0.7.0b1

- autogen/version.py
> Bump version to 0.7

- website/talks/2024-12-19-special_talk/index.mdx
> Add swe bench talks

- autogen/agentchat/contrib/captainagent/__init__.py
- autogen/agentchat/contrib/captainagent/agent_builder.py
- autogen/coding/jupyter/helpers.py
- autogen/formatting_utils.py
- autogen/logger/logger_factory.py
- autogen/logger/logger_utils.py
- autogen/logger/sqlite_logger.py
- autogen/messages/client_messages.py
- autogen/messages/print_message.py
- autogen/types.py
- website/blog/2025-01-10-WebSockets/index.mdx
- website/mint.json
> Latest talk added to website

- autogen/agentchat/contrib/reasoning_agent.py
Overall documentation improvement of the file of the new Reasoning Agent.
Closes #488
> Update reasoning agent documentation

- autogen/token_count_utils.py
- test/test_token_count.py
When counting tokens for deepsek models, return the number of tokens as the gpt-4-0613 was used
Closes #452
> Fix _num_token_from_messages for DeepSeek models

- .github/workflows/docs-test.yml
> Fix docs CI

- autogen/version.py
> Bump version to 0.7.1

- dotnet/website/articles/getting-start.md
Corrected `specifying label the label "donet" ` to `specifying the label "donet" `
> Improve Grammar

- dotnet/website/articles/Built-in-messages.md
Corrected `possilbe` to `possible`
> Improve Grammar in Docs

- .github/workflows/core-test.yml
- scripts/test-skip-llm.sh
- test/agentchat/test_cache_agent.py
- test/cache/test_redis_cache.py
- test/coding/test_commandline_code_executor.py
- test/coding/test_embedded_ipython_code_executor.py
- test/conftest.py
- test/test_code_utils.py
- website/docs/contributor-guide/tests.mdx
> Use pytest markers instead of --skip-redis and --skip-docker flags

- notebook/agentchat_structured_outputs.ipynb
Change `@assistant.register_for_execution()` to `@user_proxy.register_for_execution()` otherwise the the function will not be found:
```console
***** Suggested tool call (call_OFZLsxLmk2WhAx95jtI0kxdv): add *****
Arguments: 
{"x":3,"y":4}
********************************************************************
--------------------------------------------------------------------------------
User_proxy (to Math_solver):
***** Response from calling tool (call_OFZLsxLmk2WhAx95jtI0kxdv) *****
Error: Function add not found.
**********************************************************************
```
Closes #533
> Fix structured outputs notebook

- test/agentchat/test_agent_logging.py
- test/agentchat/test_assistant_agent.py
- test/agentchat/test_async.py
- test/agentchat/test_async_get_human_input.py
- test/agentchat/test_chats.py
- test/agentchat/test_conversable_agent.py
- test/agentchat/test_dependancy_injection.py
- test/conftest.py
Refactor LLM tests to use parameterized fixtures with dynamic marking
Closes #521
> Refactor LLM tests to use parameterized fixtures with dynamic marking

- MAINTAINERS.md
- NOTICE.md
- pyproject.toml
going through the project about wording
> modify wording in doc

- .pre-commit-config.yaml
- pyproject.toml
- test/tools/test_function_utils.py
> Packages updated

- test/interop/crewai/test_crewai.py
- test/interop/test_interoperability.py
CrewAI have updated their tool description for the tool we use in our tests.
Closes #561
> Updated test of CrewAI tool description

- test/interop/crewai/test_crewai.py
- test/interop/test_interoperability.py
> [Chore]: CrewAI tests updated due to the new version of CrewAI

- autogen/agentchat/realtime_agent/clients/oai_realtime_client.py
- notebook/agentchat_realtime_swarm_webrtc.ipynb
- notebook/agentchat_realtime_webrtc/static/WebRTC.js
- notebook/agentchat_realtime_webrtc/static/main.js
- notebook/agentchat_realtime_webrtc/templates/chat.html
minimizes delay when establishing connection to RealTime agent with WebRTC
Addresses #509
> 0509 audio starts before sesssion

- test/agentchat/test_agent_logging.py
- test/agentchat/test_assistant_agent.py
- test/agentchat/test_async.py
- test/agentchat/test_async_get_human_input.py
- test/agentchat/test_chats.py
- test/agentchat/test_conversable_agent.py
- test/agentchat/test_dependancy_injection.py
- test/conftest.py
- test/test_conftest.py
This is needed because Anthropic and Gemini tests are not being run.  Explained in #582 
Closes #582
> Fix gemini and anthropic tests

- test/website/test_process_notebooks.py
- website/process_notebooks.py
> [Docs] Remove duplicate author information from blog posts

- autogen/agentchat/contrib/swarm_agent.py
> Minor Bug Fix for swarm

- website/mint-json-template.json
> [Docs] Add Google analytics

- test/cache/test_cache.py
- test/oai/test_together.py
> Fix failing tests with optional imports

- autogen/agentchat/contrib/captainagent/tools/information_retrieval/arxiv_download.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/arxiv_search.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/image_qa.py
> Fix missed third party imports in autogen files

- autogen/version.py
> Update version to v0.7.2b1

- .github/workflows/core-llm-test.yml
- pyproject.toml
- scripts/test-core-llm.sh
- scripts/test-skip-llm.sh
- test/conftest.py
- test/test_conftest.py
> Add deepseek llm-s to CI testing

- notebook/agentchat_groupchat_customized.ipynb
The Custom GroupChat speaker selection method had a typo and needed an update to AG2.
N/A
> Update text in GroupChat customized speaker selection notebook

- autogen/import_utils.py
> Remove debugging print

- website/talks/2024-12-19-special_talk/index.mdx
add YouTube recording to swe-bench talk
> update YouTube link to sew-bench talk

- scripts/pre-commit-license-check.py
> Fix licence check

- README.md
Emojis were not shown properly on pypi since the wrong formatting was used.
Closes #568
> fixed emojis on pypi

- notebook/JSON_mode_example.ipynb
- notebook/agentchat_RetrieveChat_qdrant.ipynb
- notebook/agentchat_memory_using_mem0.ipynb
This pull request addresses fixes and updates to the following files:
- `agentchat_memory_using_mem0.ipynb`
- `agentchat_RetrieveChat_qdrant.ipynb`
- `JSON_mode_example.ipynb`
Changes include corrections to text and code formatting, ensuring consistency across the notebook files.
- Issue #[Issue Number] (if applicable)
- Fixed typo: "numnber" changed to "number".
- Improved clarity by rewording comments.
- Corrected some variable names for better understanding.
- Fixed typo: "functionalites" changed to "functionalities".
- Updated description of the agent's functionality for clarity.
- Corrected code formatting for better readability.
- Fixed typo: "anwser" changed to "answer".
- Improved consistency in formatting for JSON-related code blocks.
1. Review the changes made in the respective …
> Fix updates

- test/agentchat/test_cache_agent.py
- test/agentchat/test_conversable_agent.py
- test/conftest.py
`gemini-pro` is deprecated and the tests are often failing with it
Closes #670
> Use gemini flash instead of pro in tests

- .github/workflows/test-with-optional-deps.yml
> Add docs test to CI

- test/conftest.py
- test/oai/test_anthropic.py
> Update Claude Sonnet to 3.5 in tests

- notebook/agentchat_agentoptimizer.ipynb
- test/agentchat/test_function_call_groupchat.py
Removed "The" for grammatical correctness
> Removed "The" 

- autogen/_website/process_notebooks.py
- test/website/test_process_notebooks.py
- website/docs/.gitignore
- website/docs/use-cases/.gitignore
- website/docs/use-cases/community-gallery/community-gallery.mdx
- website/docs/use-cases/notebooks/Notebooks.mdx
- website/mint-app-gallery-deps.js
- website/mint-json-template.json.jinja
> [Docs] Populate notebooks and community gallery section under use cases

- autogen/version.py
> Update version to 0.7.3

- notebook/agentchat_assistant_agent_standalone.ipynb
- notebook/agents_websurfer.ipynb
- notebook/tools_browser_use.ipynb
- notebook/tools_browser_use_deepseek.ipynb
- notebook/tools_crawl4ai.ipynb
Spelling and grammar tidy on recent notebooks.
N/A
> WebSurferAgent and Browser Tool notebook tidy

- test/agentchat/test_assistant_agent.py
> Fix failing tests

- website/contributor-guide/docker.mdx
- website/contributor-guide/setup-development-environment.mdx
- website/faq/FAQ.mdx
- website/mint-json-template.json.jinja
> How to setup devcontainer

- test/agentchat/contrib/test_web_surfer.py
- test/test_browser_utils.py
Tests are failing: https://github.com/ag2ai/ag2/actions/runs/13067381615/job/36464709480
Closes #740
> Fix incorrect BLOG_POST_URL in tests

- website/_blogs/2025-01-31-WebSurferAgent/index.mdx
> Add WebSurferAgent blog

- .github/workflows/contrib-graph-rag-tests.yml
- .github/workflows/contrib-llm-test.yml
- .github/workflows/contrib-test.yml
- .github/workflows/core-llm-test.yml
- .github/workflows/core-test.yml
- .github/workflows/test-with-optional-deps.yml
> Upload coverage report to codecov.io using codecov token

- website/docs/user-guide/advanced-concepts/resuming-group-chat.mdx
- website/docs/user-guide/advanced-concepts/swarm-deep-dive.mdx
- website/docs/user-guide/basic-concepts/llm-configuration.mdx
- website/docs/user-guide/basic-concepts/swarm.mdx
- website/mint-json-template.json.jinja
Restored Resuming a Group Chat documentation and more fixed links
N/A
> [Docs] Restored Resuming a Group Chat documentation and more fixed links

- autogen/_website/__init__.py
- autogen/agentchat/contrib/__init__.py
- autogen/agentchat/contrib/capabilities/__init__.py
- autogen/agentchat/contrib/captainagent/__init__.py
- autogen/agentchat/contrib/captainagent/tools/__init__.py
- autogen/agentchat/contrib/graph_rag/__init__.py
- autogen/agentchat/contrib/vectordb/__init__.py
- autogen/agentchat/realtime/experimental/audio_adapters/__init__.py
- autogen/coding/__init__.py
- autogen/coding/jupyter/__init__.py
- autogen/extensions/__init__.py
- scripts/pre-commit-license-check.py
- test/agentchat/realtime_agent/clients/__init__.py
- test/coding/__init__.py
- test/website/__init__.py
> Add missing licence headers

- website/mint-style.css
> [Docs] Fix popular resources text color in dark mode

- website/package-lock.json
- website/package.json
This PR fixes the vulnerability issue found in one of the packages.
Closes #760
> [Docs] Fix vulnerability issue

- website/snippets/data/GalleryItems.mdx
- website/static/img/gallery/agent-e.png
> Add Agent-E to community gallery

- test/agentchat/test_function_call.py
- test/agentchat/test_tool_calls.py
Remove the `print`s of conversations in tests, that potentially leak sensitive information, detected by github security scan
Closes #797
> Remove sensitive prints

- website/mint-json-template.json.jinja
> [Docs] Update X account url

- .github/workflows/docs-check-broken-links.yml
> Add read permission to check broken links workflow

- website/mint-json-template.json.jinja
> [Docs] Set up redirects for old URLs

- notebook/agentchat_realtime_gemini_swarm_websocket.ipynb
- notebook/agentchat_realtime_swarm.ipynb
- notebook/agentchat_realtime_swarm_webrtc.ipynb
- notebook/agentchat_realtime_swarm_websocket.ipynb
This PR will update rwaltime swarm notebook examples to allign with the new swarm API desing
Closes #831
> Update realtime swarm notebooks to new swarm API

- pyproject.toml
> Bump dev and test dependency versions

- autogen/interop/pydantic_ai/pydantic_ai.py
- pyproject.toml
- test/interop/pydantic_ai/test_pydantic_ai.py
> Bump pydantic-ai version

- pyproject.toml
> Bump mypy version

- autogen/agentchat/contrib/captainagent/tools/data_analysis/shapiro_wilk_test.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/arxiv_download.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/arxiv_search.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/extract_pdf_image.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/extract_pdf_text.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/get_youtube_caption.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/image_qa.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/optical_character_recognition.py
- autogen/agentchat/contrib/captainagent/tools/information_retrieval/transcribe_audio_file.py
- autogen/agentchat/contrib/captainagent/tools/math/calculate_circle_area_from_diameter.py
- autogen/agentchat/contrib/captainagent/tools/math/calculate_matrix_power.py
- autogen/agentchat/contrib/captainagent/tools/math/complex_numbers_product.py
- autogen/agentchat/contrib/captainagent/tools/math/compute_currency_conversion.py
Minor changes to captain agent tools
- Fix "attempted relative import" (change `from ......coding` to `from autogen.coding`
- Update image_qa: change requirement from `PIL` to `pillow`
- Fix typo in "get_youtube_caption"
> update captain agent tools

- autogen/version.py
- pyproject.toml
> version bump to v0.7.4

- .muffet-excluded-links.txt
- README.md
- autogen/oai/client.py
- autogen/oai/completion.py
- notebook/agentchat_agentops.ipynb
- notebook/autogen_uniformed_api_calling.ipynb
- website/_blogs/2023-04-21-LLM-tuning-math/index.mdx
- website/_blogs/2023-05-18-GPT-adaptive-humaneval/index.mdx
- website/docs/faq/FAQ.mdx
- website/docs/user-guide/getting-started/Getting-Started.mdx
> [Docs] Fix broken links

- .github/workflows/contrib-graph-rag-tests.yml
- pyproject.toml
FalkorDB tests are failing because they need access to `OpenAI` secrets. I have added environment to provide access to secrets. 
Closes #894
> Run GraphRag tests with openai secrets

- autogen/_website/generate_api_references.py
- autogen/doc_utils.py
- website/generate_api_references.py
> [Docs] Prevent export module decorator from modifying the   module   of a symbol for docs generation

- .github/workflows/contrib-graph-rag-tests.yml
- .github/workflows/contrib-llm-test.yml
- .github/workflows/contrib-test.yml
- .github/workflows/core-llm-test.yml
- .github/workflows/core-test.yml
- .github/workflows/test-with-optional-deps.yml
- pyproject.toml
- scripts/show-coverage-report.sh
> Show coverage report and fix workflow discrepancies

- autogen/oai/client.py
- notebook/agentchat_structured_outputs.ipynb
- test/agentchat/test_structured_output.py
> Implement option to add response_format to llm_config

- notebook/agents_deep_researcher.ipynb
> Update DeepResearchAgent notebook example

- README.md
The developer guide link on the website is no longer working.
> Fix develop guide link

- .github/workflows/contrib-graph-rag-tests.yml
> Use proper checkout and check user permission in graphrag integration tests

- autogen/agentchat/realtime/experimental/realtime_agent.py
- website/_blogs/2025-01-09-RealtimeAgent-over-WebRTC/index.mdx
> [Docs] RealTime WebRTC Blog Polishing

- .coveragerc
- pyproject.toml
> Run codecov only for autogen instead of running for all py files in root

- .github/workflows/test-integration.yml
> Update package installation in test-integration.yml

- .secrets.baseline
- autogen/_website/process_notebooks.py
- notebook/agentchat_groupchat_vis.ipynb
- test/website/test_process_notebooks.py
> [Docs] Show the images referred in the notebooks in docs

- test/agentchat/realtime_agent/clients/test_gemini_realtime_client.py
> Handle case in test where agent finishes speaking before cancelation

- autogen/oai/gemini.py
- pyproject.toml
This PR fixes https://discord.com/channels/1153072414184452236/1339016871004868628/1339016871004868628
Closes #934
> Fix response_format passing to VertexAI

- autogen/agentchat/contrib/rag/docling_query_engine.py
- notebook/docling_md_query_engine.ipynb
1. Added an api to get collection name for indexed documents
2. Updated doc strings and the notebook
> Update query engine and notebook

- autogen/agentchat/groupchat.py
- autogen/messages/agent_messages.py
- autogen/version.py
- test/messages/test_agent_messages.py
> Release 0.7.4b2

- README.md
Add a badge in the `README.md` file that dynamically renders supported Python version from PyPi registry.
> Fix supported python version in the README file

- autogen/import_utils.py
> [Chore] Cleanup

- .github/workflows/core-llm-test.yml
- .github/workflows/test-integration.yml
> Check integration test merge queue

- .github/workflows/deploy-website-mintlify.yml
- .github/workflows/docs-check-broken-links.yml
> Fix docs workflows

- .secrets.baseline
- test/oai/test_utils.py
> Remove obsolete deepseek pricing test

- website/mako_templates/text.mako
> [Docs] Update docstring formatting

- autogen/oai/gemini.py
- pyproject.toml
> Update google-genai version

- website/snippets/components/ExploreContent.mdx
> [Docs] Fix broken links in home page

- .github/workflows/integration-test.yml
- scripts/integration-test.sh
> Add integration-test.sh and refactor CI

- website/snippets/python-examples/swarm.mdx
register_hand_off is a stand-alone function now.
> [Docs] Change register_hand_off function calls in swarm demo

- codecov.yml
> Add codecov configuration and disable codecov comments

- website/snippets/python-examples/swarm.mdx
- website/snippets/python-examples/swarmenhanced.mdx
Current demo code is not runnable.
Updated and formatted the code.
> [Docs] Update website demo code so that it is runnable

- website/docs/home/home.mdx
> [Docs] Fix broken link in homepage

- autogen/oai/client.py
- test/oai/test_client.py
> Cache seed usage log changed from info to debug level

- website/docs/user-guide/reference-agents/communication-agents.mdx
> chore: remove redundant word

- notebook/agents_deep_researcher.ipynb
- notebook/agents_document_agent.ipynb
- website/docs/user-guide/reference-agents/documentagent.mdx
- website/docs/user-guide/reference-agents/index.mdx
- website/mint-json-template.json.jinja
> Add web documentation for document agent

- .github/workflows/notify-codecov.yml
- codecov.yml
> Manually notify codecov to make PR comment with coverge percentage

- .github/workflows/contrib-test.yml
- .github/workflows/core-llm-test.yml
- .github/workflows/core-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/test-with-optional-deps.yml
- codecov.yml
> Remove after_n_builds param

- .github/workflows/deploy-website.yml
> [Docs] Add google analytics to the gh-pages domain

- .github/workflows/core-test.yml
- .github/workflows/deploy-website-mintlify.yml
- .github/workflows/test-with-optional-deps.yml
> Remove merge_group check from unnecessary workflows

- website/docs/user-guide/advanced-concepts/groupchat/custom-group-chat.mdx
> [Docs] Fix broken image path

- autogen/agents/experimental/document_agent/document_agent.py
- notebook/agents_docagent.ipynb
`initiate_task` and `execute_rag_query` needed docstrings for better LLM usage. Improved the demo notebook to provide more robust workflow. 
N/A
> Further improvements to DocAgent and demo

- .github/workflows/contrib-graph-rag-tests.yml
- .github/workflows/contrib-llm-test.yml
- .github/workflows/contrib-test.yml
- .github/workflows/core-llm-test.yml
- .github/workflows/core-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/test-with-optional-deps.yml
- .github/workflows/type-check.yml
> Disable workflow runs for all branches except on main branch on schedule

- autogen/oai/client.py
> Enhance typing and docs in oai client

- notebook/agentchat_nestedchat_optiguide.ipynb
- test/agentchat/test_agent_logging.py
- website/docs/user-guide/advanced-concepts/groupchat/custom-group-chat.mdx
**This PR includes the following changes:**
- Fixed typo in `test_agent_logging.py:` `strugling` -> `struggling`
- Fixed typo in docs: `Engineer` capitalization consistency
- Added `summary_method` field to `writer_chat_queue` format
- Improved code formatting and readability
These changes help maintain consistent documentation and fix minor text issues across the codebase.
> Fix typos and improve documentation formatting

- scripts/pre-commit-license-check.py
Skip local untracked git files when checking license header. Grab the untracked files by git commit --porcelain
> [CI/CD] Only check tracked files in git pre-submit

- autogen/messages/agent_messages.py
- test/messages/test_agent_messages.py
> Fix serialization of TextMessage containing PIL image

- .pre-commit-config.yaml
- autogen/agentchat/contrib/graph_rag/falkor_graph_rag_capability.py
- notebook/agentchat_swarm_graphrag_telemetry_trip_planner.ipynb
- notebook/agentchat_swarm_graphrag_trip_planner.ipynb
- test/agentchat/contrib/graph_rag/trip_planner_data/attractions.jsonl
- test/agentchat/contrib/graph_rag/trip_planner_data/cities.jsonl
- test/agentchat/contrib/graph_rag/trip_planner_data/restaurants.jsonl
> Add jsonl files and use it to initiate falkordb

- autogen/_website/generate_mkdocs.py
> Fix path comparison for Windows compatibility

- autogen/messages/agent_messages.py
- test/messages/test_agent_messages.py
> Move PIL to optional import block

- autogen/_website/generate_mkdocs.py
autogen/_website/generate_mkdocs.py
mint_inpur_dir - mint_input_dir
> fix function errors

- autogen/version.py
> Bump version to 0.7.6rc0

- test/agentchat/contrib/capabilities/test_image_generation_capability.py
- test/agentchat/contrib/capabilities/test_teachable_agent.py
- test/agentchat/contrib/test_agent_builder.py
- test/agentchat/contrib/test_gpt_assistant.py
- test/agentchat/contrib/test_lmm.py
- test/agentchat/contrib/test_reasoning_agent.py
- test/agentchat/contrib/test_swarm.py
- test/agentchat/contrib/test_web_surfer.py
- test/agentchat/realtime_agent/realtime_test_utils.py
- test/agentchat/test_structured_output.py
- test/oai/test_gemini.py
- test/test_logging.py
Further test updates to cater for openai becoming an optional dependency.
N/A
> Further test updates to cater for openai dependency

- autogen/oai/client.py
- test/agentchat/contrib/capabilities/test_vision_capability.py
- test/agentchat/contrib/test_llava.py
- test/agentchat/realtime_agent/test_e2e.py
- test/agentchat/realtime_agent/test_swarm_start.py
- test/agentchat/test_agent_logging.py
- test/test_retrieve_utils.py
Further changes to tests to accommodate openai as an optional dependency.
N/A
> Further changes to accommodate openai as dependency (P3)

- test/agentchat/test_conversable_agent.py
- test/agentchat/test_groupchat.py
Deepseek tests update for openai dependency
N/A
> Deepseek tests update for openai dependency

- website/docs/faq/FAQ.mdx
- website/docs/installation/Installation.mdx
- website/docs/user-guide/advanced-concepts/rag.mdx
changed:
of AG2 - of the AG2
Create and active - Create and activate
by giving it - by providing
> spelling errors

- autogen/agentchat/contrib/reasoning_agent.py
- test/agentchat/contrib/test_reasoning_agent.py
Handles the comments in #1140.
> [comments handling] Add prompt rewriting for multiple messages in ReasoningAgent

- notebook/agentchat_oai_code_interpreter.ipynb
> Remove whitespace from the agent name

- autogen/agentchat/contrib/captainagent/agent_builder.py
- test/agentchat/contrib/test_agent_builder.py
> Use kwargs to create agent_configs in AgentBuilder

- autogen/agents/experimental/document_agent/chroma_query_engine.py
> Convert input_docs to list before passing to SimpleDirectoryReader

- notebook/agentchat_realtime_swarm.ipynb
- notebook/agentchat_realtime_swarm_webrtc.ipynb
- notebook/agentchat_realtime_swarm_websocket.ipynb
- notebook/agentchat_swarm.ipynb
- notebook/agentchat_swarm_graphrag_telemetry_trip_planner.ipynb
- notebook/agentchat_swarm_graphrag_trip_planner.ipynb
> Fix swarm doc link

- autogen/agentchat/contrib/swarm_agent.py
- test/agentchat/contrib/test_swarm.py
> Use pydantic's model_dump_json instead of json.dumps when available

- pyproject.toml
Fixes #1236 by downgrading google-genai to 1.3.0
> Downgrade google-genai to working version

- test/agentchat/contrib/test_swarm.py
One of the swarm tests required the openai package installation and was causing tests to fail.
N/A
> Fix swarm test requiring OpenAI package import

- autogen/version.py
- test/agentchat/contrib/test_swarm.py
> Bump version to 0.8.0

- autogen/agentchat/contrib/swarm_agent.py
- notebook/agentchat_groupchat_tools.ipynb
- website/docs/user-guide/advanced-concepts/groupchat/tools.mdx
- website/mint-json-template.json.jinja
> Add user guide for GroupChat tool calling

- notebook/agentchat_structured_outputs.ipynb
> Fix formating issue

- autogen/tools/dependency_injection.py
> Fix issubclass checking error in dependency_injection

- autogen/agentchat/contrib/agent_eval/README.md
- autogen/agentchat/contrib/capabilities/transforms_util.py
autogen/agentchat/contrib/agent_eval/README.md
has been - have been
autogen/agentchat/contrib/capabilities/transforms_util.py
cachedd - cached
> fix issues 

- autogen/agentchat/contrib/rag/mongodb_query_engine.py
> Fix failing type checks

- website/docs/user-guide/advanced-concepts/groupchat/custom-group-chat.mdx
- website/docs/user-guide/advanced-concepts/groupchat/tools.mdx
- website/docs/user-guide/advanced-concepts/rag.mdx
- website/docs/user-guide/advanced-concepts/realtime-agent/index.mdx
- website/docs/user-guide/advanced-concepts/swarm/deep-dive.mdx
- website/docs/user-guide/advanced-concepts/swarm/use-case.mdx
- website/mint-json-template.json.jinja
> Docs Polishing

- notebook/agentchat_realtime_swarm.ipynb
> [Docs] Add realtime tag in metadata

- website/docs/user-guide/reference-agents/captainagent.mdx
- website/docs/user-guide/reference-agents/communication-platforms/discordagent.mdx
- website/docs/user-guide/reference-agents/communication-platforms/slackagent.mdx
- website/docs/user-guide/reference-agents/communication-platforms/telegramagent.mdx
- website/docs/user-guide/reference-agents/index.mdx
- website/docs/user-guide/reference-agents/reasoningagent.mdx
- website/docs/user-guide/reference-tools/communication-platforms/discord.mdx
- website/docs/user-guide/reference-tools/communication-platforms/slack.mdx
- website/docs/user-guide/reference-tools/communication-platforms/telegram.mdx
> Minor documentation updates

- autogen/oai/gemini.py
- pyproject.toml
> Upgrade google genai version

- .github/workflows/contrib-llm-test.yml
> Run captain agent tests with agent builder

- autogen/oai/oai_models/chat_completion_message.py
> Update chat completion pydantic models

- MAINTAINERS.md
> Add row to MAINTAINERS.md

- autogen/oai/ollama.py
- pyproject.toml
- test/oai/test_ollama.py
Fixes support for instantiating and use of the Ollama client.
Closes #1340
> Ollama response_format fix

- autogen/agents/experimental/document_agent/chroma_query_engine.py
> Handle query_engine response while contructing AnswerWithCitations

- autogen/llm_config.py
- autogen/oai/cohere.py
- test/oai/test_anthropic.py
- test/oai/test_cohere.py
- test/test_llm_config.py
> Accept config with and without config_list in LLMConfig

- autogen/json_utils.py
- autogen/oai/gemini.py
- pyproject.toml
- test/test_json_utils.py
- test/tools/experimental/google_search/test_google_search.py
> Removed jsonref package as optional dependancy of gemini

- autogen/version.py
> Version bump 0.8.2

- .github/workflows/mkdocs-check-broken-links.yml
- scripts/broken-links-check.sh
> [Docs] Add broken link checker for mkdocs site

- autogen/tools/experimental/browser_use/browser_use.py
This is partial fix for issue #1420
> BrowserUseTool quick fix for multiple tool calls

- autogen/llm_config.py
- autogen/oai/bedrock.py
- test/oai/test_bedrock.py
- test/test_llm_config.py
> Add voice as parameter and use SecretStr for relevant fields

- autogen/agentchat/conversable_agent.py
- autogen/llm_config.py
- test/test_llm_config.py
> Copy llmconfig

- autogen/version.py
> Bump 0.8.3

- notebook/agentchat_groupchat_tools.ipynb
- notebook/agentchat_microsoft_fabric.ipynb
- notebook/agentchat_quickstart_examples.ipynb
- notebook/mongodb_query_engine.ipynb
- notebook/oai_chatgpt_gpt4.ipynb
- notebook/oai_completion.ipynb
- notebook/tools_google_search.ipynb
> updated notebooks missing front matter metadata

- test/oai/test_anthropic.py
- test/oai/test_cerebras.py
Expected parameters for tests for Anthropic and Cerebras failed due to new Tool Choice parameter.
N/A
> Tool Choice test updates for new parameters

- autogen/version.py
> Bump version to 0.8.4

- autogen/agentchat/contrib/rag/mongodb_query_engine.py
> Fix failing type checks for retrievechat

- autogen/oai/openai_utils.py
- test/oai/test_utils.py
> Add deprecation warning to llm config utils functions

- autogen/oai/gemini_types.py
- test/oai/test_gemini_types.py
> Remove unncessary model classes and polish test cases

- autogen/tools/experimental/perplexity/perplexity_search.py
- test/tools/experimental/perplexity/test_perplexity.py
- website/docs/user-guide/reference-tools/perplexity-search.mdx
> adding comprehensive error handling to prevent unexpected crashes

- .github/workflows/deploy-website.yml
> [Docs] Copy latest docs to root for direct URL access

- autogen/_website/generate_mkdocs.py
- website/docs/contributor-guide/documentation.mdx
> [Docs] Update contribution guidelines

- notebook/run_and_event_processing.ipynb
- website/docs/_blogs/2025-01-31-WebSurferAgent/index.mdx
- website/docs/home/quick-start.mdx
- website/docs/user-guide/reference-agents/docagent.mdx
- website/docs/user-guide/reference-tools/google-api/google-search.mdx
- website/docs/user-guide/reference-tools/google-api/youtube-search.mdx
- website/snippets/python-examples/conversableagentchat.mdx
- website/snippets/python-examples/structured_output.mdx
- website/snippets/reference-tools/google-drive.mdx
Provide some basic document on run and the RunResponse protocol's process method.
N/A
> Run and notebook tweaks

- notebook/mcp_client.ipynb
- website/docs/user-guide/basic-concepts/tools/mcp/client.mdx
- website/snippets/mcp/client.mdx
> Update MCP guide with Server-Sent Events messaging

- notebook/mcp_client.ipynb
- website/snippets/mcp/client.mdx
> Fix references

- website/blogs_and_user_stories_authors.yml
- website/docs/user-stories/2025-04-03-Fortune-500-RAG-Chatbot/img/01.png
- website/docs/user-stories/2025-04-03-Fortune-500-RAG-Chatbot/img/02.png
- website/docs/user-stories/2025-04-03-Fortune-500-RAG-Chatbot/img/banner.png
- website/docs/user-stories/2025-04-03-Fortune-500-RAG-Chatbot/img/profile.png
- website/docs/user-stories/2025-04-03-Fortune-500-RAG-Chatbot/index.mdx
> [Docs] Publish fortune 500 RAG chatbot user story

- autogen/agents/experimental/reasoning/reasoning_agent.py
This PR fixes a bug that a string was recreated instead of appended.
> ReasoningAgent Fix string append bug

- website/docs/user-guide/advanced-concepts/llm-configuration-deep-dive.mdx
- website/docs/user-guide/advanced-concepts/swarm/deep-dive.mdx
- website/docs/user-guide/basic-concepts/installing-ag2.mdx
- website/docs/user-guide/basic-concepts/llm-configuration/llm-configuration.mdx
- website/docs/user-guide/basic-concepts/orchestration/ending-a-chat.mdx
- website/mkdocs/mkdocs.yml
Fixing the display of Mermaid diagrams and lists with MkDocs.
N/A
> Document tidy

- website/blogs_and_user_stories_authors.yml
- website/docs/user-stories/2025-04-04-AgentWeb/img/01.png
- website/docs/user-stories/2025-04-04-AgentWeb/img/banner.png
- website/docs/user-stories/2025-04-04-AgentWeb/img/profile.png
- website/docs/user-stories/2025-04-04-AgentWeb/index.mdx
- website/mkdocs/docs/javascripts/extra.js
- website/mkdocs/docs/stylesheets/extra.css
> [Docs] Publish AgentWeb's user story

- autogen/_website/generate_mkdocs.py
- test/website/test_generate_mkdocs.py
> Fix failing mkdocs tests

- website/snippets/python-examples/conversableagentchat.mdx
The updated ConversableAgent documentation doesn't have max turns or user input enabled so it doesn't run correctly.
N/A
> Fix ConversableAgent documentation

- pyproject.toml
> Fix failing CI tests and update dependency versions

- autogen/agentchat/contrib/swarm_agent.py
- autogen/agentchat/conversable_agent.py
- autogen/io/run_response.py
- notebook/run_and_event_processing.ipynb
- test/agentchat/test_event_streaming.py
This PR will add a cost attr to the RunResponse and AsyncRunResponse that will be set at the end of the chat, containing the chat cost information.
Closes #1571
> Add Cost to RunResponse and AsyncRunResponse

- autogen/_website/generate_mkdocs.py
- test/website/test_generate_mkdocs.py
> [Docs] Add community insights to navigation

- autogen/_website/generate_mkdocs.py
- test/website/test_generate_mkdocs.py
- website/docs/user-guide/advanced-concepts/swarm/deep-dive.mdx
- website/docs/user-guide/advanced-concepts/swarm/use-case.mdx
- website/docs/user-guide/basic-concepts/tools/basics.mdx
- website/docs/user-guide/reference-agents/deepresearchagent.mdx
- website/docs/user-guide/reference-agents/docagent-performance.mdx
- website/docs/user-guide/reference-agents/docagent.mdx
- website/docs/user-guide/reference-agents/reasoningagent.mdx
- website/docs/user-guide/reference-agents/websurferagent.mdx
- website/docs/user-guide/reference-tools/crawl4ai.mdx
- website/mint-json-template.json.jinja
> [Docs] Reorder main Navigation

- website/docs/user-guide/basic-concepts/llm-configuration/llm-configuration.mdx
This PR updates the `LLMs.md` file with the latest LLM configuration details for AG2. It includes:
- Clear instructions on setting up LLMs from different providers.
- Improved examples for configuring multiple models using `LLMConfig`.
- Security best practices for handling API keys.
- A well-structured format to enhance readability.
- Modified `LLMs.md` to include the latest LLM setup details.
- Enhanced explanation of environment variables.
- Verify the installation commands for different providers.
- Check the example code snippets for correctness.
- Ensure environment variable instructions are clear and accurate.
N/A
- This update aligns with AG2's recent changes and best practices.
- Feedback and suggestions are welcome! 🚀
> feat: Update LLM configuration documentation

- autogen/version.py
> Version updated to 0.8.6beta0

- autogen/agentchat/contrib/graph_rag/falkor_graph_query_engine.py
> fix spelling error falkor_graph_query_engine.py

- autogen/version.py
> Bump version to 0.8.6

- autogen/_website/generate_mkdocs.py
> [Docs] Remove file extension when constructing the notebook URL's

- test/tools/experimental/messageplatform/slack/test_slack.py
> Fix failing slack tests

- website/blogs_and_user_stories_authors.yml
- website/docs/user-stories/2025-04-11-Productionizing-OSS-Agents/img/banner.png
- website/docs/user-stories/2025-04-11-Productionizing-OSS-Agents/img/profile.png
- website/docs/user-stories/2025-04-11-Productionizing-OSS-Agents/index.mdx
- website/mkdocs/docs/stylesheets/extra.css
Closes #1627 
- [x ] I've included any doc changes needed for https://docs.ag2.ai/. See https://docs.ag2.ai/docs/contributor-guide/documentation to build and test documentation locally.
- [x ] I've made sure all auto checks have passed.
> [Docs] Add a new user story capturing Jason's GCN talk

- autogen/agents/experimental/__init__.py
- autogen/agents/experimental/wikipedia/__init__.py
- autogen/agents/experimental/wikipedia/wikipedia.py
- autogen/tools/experimental/wikipedia/wikipedia.py
- notebook/agents_wikipedia.ipynb
- test/agents/experimental/wikipedia/__init__.py
- test/agents/experimental/wikipedia/test_wikipedia.py
- website/docs/user-guide/reference-agents/index.mdx
- website/docs/user-guide/reference-agents/wikipediaagent.mdx
- website/mint-json-template.json.jinja
> Adding Wikipedia agent

- website/docs/user-guide/basic-concepts/tools/index.mdx
> [Docs] Update tool use documentation

- autogen/oai/client.py
> Removed unnecessary loggings

- website/blogs_and_user_stories_authors.yml
- website/docs/user-stories/2025-04-15-CMBAgent/img/banner.png
- website/docs/user-stories/2025-04-15-CMBAgent/img/boris_profile.png
- website/docs/user-stories/2025-04-15-CMBAgent/img/flow-chart.png
- website/docs/user-stories/2025-04-15-CMBAgent/img/francisco_profile.png
- website/docs/user-stories/2025-04-15-CMBAgent/img/inigo_profile.png
- website/docs/user-stories/2025-04-15-CMBAgent/img/james_profile.png
- website/docs/user-stories/2025-04-15-CMBAgent/index.mdx
- website/mkdocs/docs/stylesheets/extra.css
> [Docs] Add CMBAgent user story

- notebook/agentchat_reasoning_agent.ipynb
- website/docs/user-guide/reference-agents/reasoningagent.mdx
`ReasoningAgent`'s documentation mentions `batch_execution` instead of `batch_grading`.
> Fix batch_grading typo

- autogen/version.py
> Update version to 0.8.7

- autogen/_website/generate_mkdocs.py
- test/website/test_generate_mkdocs.py
- website/docs/community-talks/2025-04-10-NOVA/index.mdx
This pull request adds a new Community Talk entry to the website, making it accessible from the Community Insights tab.
Closes #1630
- [x ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ x] I've made sure all auto checks have passed.
> [Docs] Add NOVA community talk

- autogen/agentchat/contrib/agent_optimizer.py
`adde` - `added` --fix typo
`are arranged in are arranged in` - `are arranged in ` --fix duplicate
> fix correction agent_optimizer.py

- autogen/agentchat/conversable_agent.py
- autogen/cache/cache.py
- test/agentchat/test_conversable_agent.py
> Read from Cache context's cache

- autogen/agentchat/group/context_variables.py
- website/docs/user-guide/advanced-concepts/pattern-cookbook/pipeline.mdx
- website/docs/user-guide/advanced-concepts/pattern-cookbook/redundant.mdx
- website/docs/user-guide/advanced-concepts/pattern-cookbook/star.mdx
- website/docs/user-guide/advanced-concepts/pattern-cookbook/triage_with_tasks.mdx
Cookbook patterns updated from swarm to new group chat
N/A
> Swarm Cookbook Patterns updated for new groupchat

- .github/workflows/build-mkdocs.yml
> [Docs] Deploy docs from 0.9 branch

- .github/workflows/build-mkdocs.yml
- .github/workflows/deploy-website.yml
> [Docs] Remove copy-latest-to-root job from mkdocs workflow

- autogen/agentchat/group/multi_agent_chat.py
- autogen/events/agent_events.py
- test/agentchat/group/test_multi_agent_chat.py
- test/agentchat/test_conversable_agent.py
- test/events/test_agent_events.py
- test/test_browser_utils.py
Test fixes to accommodate 0.9. Also added the `a_initiate_group_chat` (which was not yet implemented).
N/A
> 0.9 test fixes

- website/docs/user-guide/advanced-concepts/orchestration/swarm/deprecation.mdx
Document tweaks for 0.9 documentation.
N/A
> Documentation updates for 0.9

- autogen/agentchat/__init__.py
- autogen/agentchat/contrib/swarm_agent.py
- autogen/agentchat/group/multi_agent_chat.py
- autogen/io/base.py
- autogen/io/thread_io_stream.py
- notebook/run_and_event_processing.ipynb
- test/agentchat/test_event_streaming.py
> Implement run_group_chat and a_run_group_chat

- website/blogs_and_user_stories_authors.yml
- website/docs/_blogs/2025-04-28-0.9-Release-Announcement/index.mdx
> [Docs] Write a blog post on 0.9 release

- website/docs/_blogs/2025-04-28-0.9-Release-Announcement/index.mdx
Code tweaks and minor wording updates.
N/A
> 0.9 blog code updates

- test/interop/crewai/test_crewai.py
- test/interop/test_interoperability.py
- test/oai/test_gemini_types.py
> Fix failing ci test cases

- website/docs/user-guide/basic-concepts/assets/human-in-the-loop-example.png
- website/docs/user-guide/basic-concepts/human-in-the-loop.mdx
Updating documentation assets to match our brand.
Part of #1707
> [Docs] Update diagram on Human in the Loop Example

- website/blogs_and_user_stories_authors.yml
- website/docs/user-stories/2025-04-30-Cegid-Pulse-OS/img/01.png
- website/docs/user-stories/2025-04-30-Cegid-Pulse-OS/img/banner.png
- website/docs/user-stories/2025-04-30-Cegid-Pulse-OS/img/profile.png
- website/docs/user-stories/2025-04-30-Cegid-Pulse-OS/index.mdx
> [Docs] Add cegid user story

- pyproject.toml
- test/interop/crewai/test_crewai.py
- test/interop/test_interoperability.py
> Limit litellm version in Windows

- autogen/agentchat/agent.py
- autogen/agentchat/contrib/swarm_agent.py
- autogen/agentchat/conversable_agent.py
- autogen/agentchat/group/multi_agent_chat.py
- autogen/io/run_response.py
- autogen/version.py
- test/agentchat/test_conversable_agent.py
> Add UI tool to agents

- autogen/tools/experimental/__init__.py
- autogen/tools/experimental/web_search_preview/__init__.py
- autogen/tools/experimental/web_search_preview/web_search_preview.py
- notebook/tools_web_search_preview.ipynb
- test/tools/experimental/web_search_preview/__init__.py
- test/tools/experimental/web_search_preview/test_web_search_preview.py
Enable usage of the OpenAI-s `web_search_preview`tool.
Closes #1753
> Add web search preview tool

- autogen/version.py
> Bump version to 0.9.1

- .github/workflows/python-package.yml
- autogen/version.py
> Release 0.9.1

- autogen/mcp/mcp_proxy/mcp_proxy.py
> Add requirement decorator

- website/docs/_blogs/2025-04-16-Reasoning/index.mdx
The format of the last paragraph was incorrect.
> fix a format issue in blog post

- autogen/mcp/__main__.py
- autogen/mcp/mcp_proxy/mcp_proxy.py
- autogen/mcp/mcp_proxy/patch_fastapi_code_generator.py
- autogen/oai/gemini_types.py
- pyproject.toml
- test/agentchat/contrib/test_img_utils.py
- test/oai/test_gemini_types.py
> Fix failing CI actions

- notebook/agentchat_function_call_currency_converter_tool_api.ipynb
This notebook introduces a fully autonomous, multi-currency converter workflow using AG2 agents. It improves on the existing `agentchat_function_call_currency_calculator.ipynb` by:
- Supporting any currency pair (not just USD↔EUR)
- Allowing dynamic selection between:
- GoogleSearchTool for LLM-powered rate retrieval
- Frankfurter API for deterministic, fast HTTP-based lookup
- Using AutoPattern and GroupChat for a clean orchestration
- Eliminating the need for human-in-the-loop once the prompt is submitted
This shows how AG2 agents can adaptively reason and delegate responsibilities in a structured tool-vs-code workflow.
N/A — new feature notebook inspired by existing examples.
- [ x] I've included any doc changes needed for https://docs.ag2.ai/. See …
> Add autonomous currency converter notebook using tools and API

- autogen/agentchat/conversable_agent.py
- test/agentchat/test_function_call_groupchat.py
This fix will enable async function calls in sync context by running async functions in another thread
Closes #1763
> Fix async function calling in sync runs

- autogen/version.py
> Update version to 0.9.2

- notebook/reliable_basic_example.ipynb
- notebook/reliable_google_search.ipynb
- notebook/reliable_group_chat.ipynb
Updates to ReliableTool notebooks to become visible in the documentation.
N/A
> ReliableTool notebook updates

- autogen/agents/experimental/document_agent/document_agent.py
DocAgent doesn't reliably run follow-up queries (such as in a group chat).
N/A
> Fix DocAgent to support follow-up queries

- README.md
Update 404 reference
https://docs.ag2.ai/docs/user-guide/advanced-concepts/rag
https://docs.ag2.ai/latest/docs/user-guide/advanced-concepts/rag/
> Replace 404 reference in README.md

- autogen/agentchat/groupchat.py
missing await on these lines prevent us from the resuming messages
I haven't created any should I?
> fixed await problem

- website/docs/_blogs/2025-06-12-ReAct-Loops-in-GroupChat/img/image1.png
- website/docs/_blogs/2025-06-12-ReAct-Loops-in-GroupChat/img/image2.png
- website/docs/_blogs/2025-06-12-ReAct-Loops-in-GroupChat/img/image3.png
- website/docs/_blogs/2025-06-12-ReAct-Loops-in-GroupChat/img/image4.png
- website/docs/_blogs/2025-06-12-ReAct-Loops-in-GroupChat/index.mdx
This Article introduces how to reliably implement ReAct loops within a Group Chat. It showcases a real-world example an essay evaluation system using AG2
> Article - From Reasoning to Evaluation: Advanced ReAct Loops for Multi-Agent Essay Evaluation

- website/blogs_and_user_stories_authors.yml
- website/docs/_blogs/2025-06-12-ReAct-Loops-in-GroupChat/index.mdx
Add metadata to Nipun's blog post on ReAct
N/A
> ReAct blog post configuration

- autogen/agentchat/contrib/capabilities/transforms.py
Update transform method. 
This allows to clean-up the chat history efficiently (or "hide" message from specific agents to specific agents(
> Adding exclude names option in transform

- autogen/agentchat/realtime/experimental/realtime_swarm.py
- autogen/oai/gemini.py
- autogen/oai/gemini_types.py
- autogen/oai/oai_models/chat_completion.py
- pyproject.toml
- test/agentchat/contrib/test_img_utils.py
- test/tools/experimental/reliable/test_reliable.py
- LMMtest was faling, this is a fix
- Gemini tests failed, this fixes them
- Reliable tool tests were failing with OpenAI due to a database issue (?), skipped.
> LMMTest fixes

- autogen/version.py
> Version bump to 0.9.3

- autogen/agents/experimental/websurfer/websurfer.py
- autogen/oai/gemini_types.py
- autogen/tools/experimental/__init__.py
- autogen/tools/experimental/searxng/__init__.py
- autogen/tools/experimental/searxng/searxng_search.py
- notebook/tools_searxng_search.ipynb
- test/tools/experimental/searxng/test_searxng.py
- website/docs/user-guide/reference-tools/index.mdx
- website/docs/user-guide/reference-tools/searxng-search.mdx
Adds support for searching via `searxng`
Closes #1904
> Add searxng tool and websurfer

- autogen/agents/experimental/websurfer/websurfer.py
- autogen/tools/experimental/__init__.py
- autogen/tools/experimental/firecrawl/__init__.py
- autogen/tools/experimental/firecrawl/firecrawl_tool.py
- notebook/tools_firecrawl.ipynb
- notebook/websurfer_firecrawl_example.ipynb
- test/agents/experimental/websurfer/test_websurfer.py
- test/tools/experimental/firecrawl/test_firecrawl.py
- website/docs/user-guide/reference-tools/firecrawl.mdx
- website/docs/user-guide/reference-tools/index.mdx
Add FireCrawl as a web search and URL scraping tool
Closes #1905
> Ag2 1905 add firecrawl web tool 20250620

- autogen/mcp/helpers.py
- autogen/mcp/mcp_proxy/mcp_proxy.py
- notebook/mcp/mcp_proxy.ipynb
- templates/client_template/main.jinja2
- website/snippets/mcp/client.mdx
> Add streamable-http option to mcp client

- autogen/oai/gemini.py
- Handle Gemini client finish failures more gracefully.
- Fix a bug that occurred where the message structure for tool calls wasn't being supported.
N/A
> Fix Gemini tool call message handling and handle failed responses with empty-content

- autogen/agentchat/realtime/experimental/realtime_swarm.py
- test/oai/test_responses_client.py
- Fix import path for OAI Responses test
- Add input and output guardrails to SwarmableRealtimeAgent (non-functional)
> Test updates for LLM testing

- autogen/oai/ollama.py
closes #1960 
This PR mitigates the Vulnerability CVE-2024-6982 arising from Python `eval()` by replacing `eval()` with `ast.literal_eval()`
> mitigate: Vulnerability CVE-2024-6982

- autogen/_website/generate_mkdocs.py
> fix: Correct variable name in generate_mkdocs.py

- autogen/tools/experimental/web_search_preview/web_search_preview.py
- test/oai/test_oai_models.py
> lint: fix mypy

- website/docs/contributor-guide/setup-development-environment.mdx
Fixed markup issues on docs page "Contributor Guide > Setup Development Environment":
- Fixed lists inside tabs
- Fixed tip block rendering problem
- Changed section with nested tabs
Closes #1985
> docs: fix broken markup at Contributing page

- autogen/_website/generate_mkdocs.py
- autogen/_website/process_notebooks.py
> chore: fix typo in comment sections

- autogen/oai/client.py
Added Support for Minimal Reasoning to Chat Completion
closes #2008
> feat: Add gpt-5 minimal reasoning to chat.completion

- autogen/version.py
Due to having to yank autogen==0.9.8, updating version.
N/A
> Version bump to 0.9.8.post1

- autogen/import_utils.py
- autogen/version.py
- test/test_import_utils.py
> Bump version to 0.9.9

- autogen/version.py
> Bump version to 0.9.10
