website/docusaurus.config.js, website/talks/future_talks/index.mdx
=> fix websites

.github/workflows/build.yml, .github/workflows/contrib-openai.yml, .github/workflows/contrib-tests.yml, .github/workflows/openai.yml, .github/workflows/type-check.yml, README.md, autogen/agentchat/contrib/llamaindex_conversable_agent.py, setup.py, test/agentchat/contrib/graph_rag/test_falkor_graph_rag.py, test/agentchat/test_function_and_tool_calling.py, test/test_notebook.py, website/docs/installation/Installation.mdx
With Python 3.13 released last month, any new updates or installs of Python will be version 3.13 and this is not supported at the moment for pip installing. Additionally, tests are not being run for Python 3.13.
Updated support for 3.13 for installing and testing.
Includes:
- Fix for a test related to GraphRag
- Fix for a test for llama indexindex conversable agent
- Fix for a test due to a change in [json error messages](https://github.com/python/cpython/pull/113227/files) in Python 3.13
Important:
- Numpy 2.1+ (Aug 2024) is the first version to support Python 3.13 - so we are including numpy 2.1 when using python 3.13. Hopefully this does not have any issues with other external packages.
=> Update support for Python 3.13

autogen/agentchat/contrib/swarm_agent.py
Updates to the First Speaker handling for the swarm.
Changes to `initiate_swarm_chat`:
- Will create a temporary `UserProxyAgent` agent if: only one message passed in + the message doesn't have a name + no user agent has been passed in
- Will clear the temporary UserProxyAgent's name from the chat history before returning from `initiate_swarm_chat`
- `init_agent` parameter name changed to `initial_agent` for clarity
N/A
=> Swarm - First Speaker

scripts/pre-commit-license-check.py
In my previous implementation of the license check, #90, when running the check locally with `pre-commit run` it would check all python files, irrespective of whether they were staged or not.
This update fixes that.
Also, when this runs as a GitHub action it will check against the base branch.
N/A
=> Restrict license checks to staged/committed files only

README.md, website/docs/contributor-guide/contributing.md
=> Readme enhancements

autogen/agentchat/contrib/swarm_agent.py
Bassil on discord discovered that context_variables are in the chat history.
The context_variables were being added to the messages for execution, but were not being removed again after execution.
This removes them.
N/A
=> Swarm: Fix to remove context_variables in messages

.github/workflows/contrib-graph-rag-tests.yml, autogen/agentchat/contrib/graph_rag/falkor_graph_query_engine.py, autogen/agentchat/contrib/graph_rag/falkor_graph_rag_capability.py, autogen/agentchat/contrib/graph_rag/graph_query_engine.py, autogen/agentchat/contrib/graph_rag/graph_rag_capability.py, notebook/agentchat_graph_rag_falkordb.ipynb, setup.py, test/agentchat/contrib/graph_rag/test_falkor_graph_rag.py
This PR integrates FalkorDB. It wraps FalkorDB as a GraphQueryEngine and could be added to an AG2 agent through GraphRagCapability.
I also include a notebook example to show how to use this feature.
part of #68
=> [GraphRAG] FalkorDB graph rag integration

autogen/agentchat/contrib/agent_builder.py
The current autobuild only restricts coding to Python and Shell within the CODING_AND_TASK_SKILL_INSTRUCTION section. However, this does not completely prevent the LLM from generating agents in other programming languages, such as Java_Expert or C_Expert.
Adding restrictions in the AGENT_NAME_PROMPT can address this issue.
=> limit coding to python and shell in autobuild

test/agentchat/test_async.py
The text in the sample data feed in [test_async.py](https://github.com/ag2ai/ag2/blob/4889c5858b9ba06e2fc0e44a09e192d616c26261/test/agentchat/test_async.py#L26) is triggering the Azure OpenAI content filter. This updates the text to avoid that as it's not the purpose of this test.
`
{
"title": "Palantir CEO Says Our Generation's Atomic Bomb Could Be AI Weapon - And Arrive Sooner Than You Think - Palantir Technologies  ( NYSE:PLTR ) ",
"summary": "Christopher Nolan's blockbuster movie \"Oppenheimer\" has reignited the public discourse surrounding the United States' use of an atomic bomb on Japan at the end of World War II.",
"overall_sentiment_score": 0.009687,
},
`
to
`
{
"title": "Palantir CEO Says Our Generation's Main Challenge Could Be AI Against Humanity - And Arrive Sooner Than You …
=> Update test to avoid Azure content filter

notebook/agentchat_openlit.ipynb, website/docs/topics/llm-observability.md
Hi Team, I am one of the maintainers of [OpenLIT](https://github.com/openlit/openlit) and we support Obserability for Agents built using AG2, It is all OpenTelemetry-native so the traces and metrics can be sent to any platfrom like [Grafana](https://grafana.com/docs/grafana-cloud/monitor-applications/ai-observability/introduction/) or any [OSS OTel tools](https://opentelemetry.io/blog/2024/llm-observability/)
Figured the mention here might be useful for developers using AG2 hence adding the reference in Agent Observabiliy documentation page along with a notebook
Previous PR - https://github.com/ag2ai/ag2/pull/56
=> Docs: Add OpenLIT to Agent Observability doc along with notebook

autogen/oai/client.py
This PR introduces a `_convert_to_chat_completion` method that will convert `ParsedChatCompletion` objects into `ChatCompletion` objects. The `ChatCompletion` objects are picklable superclass of `ParsedChatCompletion` which contain all the fields that we use from the response in the client, so this approach enables caching of the responses generated while using `response_format` option.
Closes #133
=> Add conversion from ParsedChatCompletion to ChatCompletion

website/docs/topics/llm_configuration.ipynb
Two links in the [LLM Configuration documentation](https://ag2ai.github.io/ag2/docs/topics/llm_configuration) are broken because they are pointing to the Microsoft repo. I updated these links to point to `ag2ai` instead.
=> Update github/microsoft/autogen links

autogen/oai/anthropic.py
Just a maintenance update to include anthropic newer model pricing info.
Info taken from [anthropic](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table) docs
=> chore(pricing): update Anthropic model pricing constants

notebook/agentchat_nested_chats_chess.ipynb
An image in the [Nested Chat Chess documentation](https://ag2ai.github.io/ag2/docs/notebooks/agentchat_nested_chats_chess/) is broken because it is linked to `/microsoft/autogen`.
=> Update github/microsoft/autogen link in chess documentation.

website/blog/2024-12-02-ReasoningAgent2/index.mdx, website/blog/2024-12-06-FalkorDB-Structured/index.mdx, website/blog/authors.yml
Update notebook links
Use links to the website for better readability and navigation.
=> Update noteobook links

autogen/oai/groq.py
The base_url functionality in Groq was not working correctly in AutoGen version 0.4.1. This PR addresses the issue by fixing the logic for handling the base_url parameter, ensuring it functions as expected.
=> fix base_url not work in groq

.github/workflows/contrib-graph-rag-tests.yml, notebook/agentchat_graph_rag_falkordb.ipynb, notebook/agentchat_swarm_graphrag_trip_planner.ipynb, setup.py
`pip install` does not allow underscores in the package extras, so the `graph_rag_falkor_db` extra is being interpreted as `graph-rag-falkor-db` and can't be found in the setup.py.
This fixes that by changing it to hyphens so they can install either:
`pip install ag2[graph_rag_falkor_db]` or `pip install ag2[graph-rag-falkor-db]`
Discord issue
=> Setup.py > underscores to hyphens fix

autogen/agentchat/contrib/graph_rag/falkor_graph_query_engine.py, notebook/agentchat_graph_rag_falkordb.ipynb
Some exceptions are not handled in explicit way. Handle those that the APIs will throw meaningful message.
Add delete API.
Follow up on #177 
tested with notebook example locally.
=> Falkor DB Query Engine: Add delete method and handle exceptions

notebook/agentchat_swarm_graphrag_telemetry_trip_planner.ipynb
Tweak text in notebook and highlight what's new. Address pre-commit issue.
N/A
=> Tweaked telemetry notebook text

autogen/agentchat/realtime_agent/function_observer.py, autogen/agentchat/realtime_agent/realtime_agent.py, autogen/agentchat/realtime_agent/twilio_observer.py
=> removing openai_ws from observers

autogen/version.py
Version > 0.5.3b1 for pip testing of new neo4j extra.
N/A
=> Version Bump 0.5.3b1

notebook/agentchat_graph_rag_neo4j.ipynb
=> Add Neo4j GraphRAG notebook to website

autogen/oai/bedrock.py, website/docs/topics/non-openai-models/cloud-bedrock.ipynb
#84 [Bug]: Code doesn't work on AWS Lambda function when deployed with attached Role to access bedrock service.
Code was not working on AWS Lambda function when deployed with attached Role to access bedrock service.
When passed credentials locally or via AWS profile, it works fine. However, it doesn't pick automatically session when deployed on AWS with managed services (eg: AWS Lambda function, Amazon ECS task, etc.) or Amazon EC2 with attached role. Although it is recommended and more secure way than creating access credentials.
I have made changes to build bedrock-runtime client directly using boto3 which uses attached Role to managed AWS service.
This is more secure way to running code over AWS. Tested it with AWS Lambda function and ECS container task.
- Implemented direct …
=> Updated bedrock.py to handle case of deploying it over Lambda function with attached role

test/agentchat/contrib/capabilities/test_image_generation_capability.py
Recently updated contrib tests had dall-e-2 supported resolutions while changing to dall-e-3, which supports different resolutions. This fixes that.
N/A
=> Updated resolutions for Dall-e-3 for Contrib tests

autogen/oai/cerebras.py, test/oai/test_cerebras.py, website/docs/topics/non-openai-models/cloud-cerebras.ipynb
Cerebras added support for Llama 3.3 70b and will be deprecating Llama 3.1 70b support soon. As a result, I've updated the examples and documentations here to reflect that.
=> Migrate Cerebras from Llama 3.1 70b to Llama 3.3 70b

autogen/version.py, test/agentchat/contrib/test_web_surfer.py, test/test_browser_utils.py
=> Bump version to 0.6.0b1

autogen/agentchat/contrib/swarm_agent.py, autogen/agentchat/realtime_agent/client.py, autogen/agentchat/realtime_agent/function_observer.py, autogen/agentchat/realtime_agent/realtime_agent.py, autogen/agentchat/realtime_agent/realtime_observer.py, autogen/agentchat/realtime_agent/twilio_observer.py, autogen/agentchat/realtime_agent/websocket_observer.py, notebook/agentchat_realtime_swarm.ipynb, pyproject.toml, setup.py, test/agentchat/realtime_agent/__init__.py, test/agentchat/realtime_agent/test_submodule.py
=> Typing fixed for realtime agent

website/blog/2024-12-02-ReasoningAgent2/index.mdx, website/blog/2024-12-20-Reasoning-Update/index.mdx
added the youtube links to the ReasoningAgent blogs.
=> fix: ReasoningAgent blog links

autogen/agentchat/__init__.py, autogen/agentchat/contrib/swarm_agent.py, autogen/agentchat/groupchat.py, test/agentchat/contrib/test_swarm.py, website/docs/topics/swarm.ipynb
Add `a_initiate_swarm_chat` for asynchronous swarm chat.
Includes considerable internal refactoring of initiate_swarm_chat into separate functions.
Includes a fix for GroupChat's `a_run_chat` to handle `NoEligibleSpeaker` exceptions.
Closes #299
=> Swarm Asynchronous initiate_swarm_chat

autogen/version.py, test/io/test_websockets.py
Bump version to 0.6.1 for release.
Includes an update for the websocket test file to handle closed connections.
N/A
=> Bump version to 0.6.1

autogen/oai/anthropic.py, autogen/oai/client.py, setup.py, test/oai/test_anthropic.py, website/docs/topics/non-openai-models/cloud-anthropic.ipynb
The changes include adding support AnthropicVertex inside oai/anthropic.py and oai/client.py, so that Anthropic models running in GCP can be used in Ag2 for building Agents.
Closes #308 
- [  ] I've made sure all auto checks have passed.
=> Adding AnthropicVertexAI API support in the Anthropic LLM lib under oai

notebook/agentchat_MathChat.ipynb, notebook/agentchat_graph_rag_falkordb.ipynb, notebook/agentchat_realtime_websocket.ipynb, notebook/config_loader_utility_functions.ipynb, website/mint.json, website/snippets/data/NotebooksMetadata.mdx
The `notebook/agentchat_realtime_websocket.ipynb` notebook is missing the front_matter metadata and because of which it is not being rendered in the documentation. This PR fixes adds the required front_matter metadata to the notebook and fixes the issue.
=> [Docs] Add missing front matter metadata in notebook

dotnet/src/AutoGen.Core/Extension/GroupChatExtension.cs
=> chore: update GroupChatExtension.cs

.github/workflows/contrib-tests.yml, test/agentchat/contrib/test_reasoning_agent.py
=> Add the ReasoningAgent to CI

setup.py, test/interop/crewai/test_crewai.py, test/interop/test_interoperability.py
Fix CrewAI interoperability tests failing.
Closes #341
=> Fix CrewAI interoperability failing tests

autogen/agentchat/contrib/graph_rag/document.py, autogen/agentchat/contrib/graph_rag/neo4j_graph_query_engine.py, test/agentchat/contrib/graph_rag/layout_parser_paper_parsed_elements.json, test/agentchat/contrib/graph_rag/test_neo4j_graph_rag.py
This PR add JSON file support to Neo4j via Llamaindex integration. 
This is a prerequisite for RAG on PDF file support. As we plan to use JSON to store the structured meta data for the parsed PDF files.
Related to #68 
```
pytest -v test/agentchat/contrib/graph_rag/test_neo4j_graph_rag.py::test_neo4j_json_auto
============================================================================================ test session starts =============================================================================================
platform linux -- Python 3.11.10, pytest-7.4.4, pluggy-1.5.0 -- /usr/local/bin/python3.11
cachedir: .pytest_cache
rootdir: /workspaces/ag2
configfile: pyproject.toml
plugins: xdist-3.6.1, cov-6.0.0, anyio-4.6.2.post1, asyncio-0.23.8
asyncio: mode=Mode.STRICT
collected 1 item …
```
=> Add JSON support for neo4j via llamaindex rag integration

autogen/agentchat/contrib/swarm_agent.py
In PR #217, the return "auto" line was lost when merging with main in the last commit. This restores it.
N/A
=> Swarm: Restore lost SWARM_MANAGER return

autogen/messages/agent_messages.py, test/messages/test_agent_messages.py
Fixes Pydantic error breaking MultimodalConversableAgent
When using the `MultimodalConversableAgent`, the `create_received_message_model` function occasionally attempts to construct a `TextMessage` by setting its `content` to a structure like `[{'type': 'text', 'text': '...'}]`.
As a result, to accommodate this structure in `TextMessage.content`, the type annotation should be updated to include `list[dict[str, str]]`.
Closes #383
=> content parameter of TextMessage class can also be list

pyproject.toml
If we don't explicitly specify `pyyaml` version, it resolves to an older version which has some issues with installing- https://github.com/yaml/pyyaml/issues/724. The fix is to simply pin the version of `pyyaml` like `pyyaml==6.0.2`. 
To prevent similar issues from happening in the future, we should use pinned versions for dev dependencies - https://github.com/ag2ai/ag2/issues/453
Closes #460
=> Fix devcontainer failing because of pyyaml version

autogen/agentchat/conversable_agent.py, autogen/agentchat/realtime_agent/realtime_agent.py, test/agentchat/contrib/capabilities/test_vision_capability.py, test/agentchat/test_conversable_agent.py, test/messages/test_agent_messages.py
This PR adds regex-based validation to the ConversableAgent class to ensure the name attribute does not contain any whitespace. A ValueError with a clear message is raised if validation fails.
Closes #451
=> Add Validation for name in ConversableAgent to Prevent Whitespace

website/_blogs/2023-12-01-AutoGenStudio/index.mdx, website/docs/autogen-studio/getting-started.mdx
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `correstly` to `correctly`
Corrected `AutoGen Studio is an low-code` to `AutoGen Studio is a low-code`
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

website/docs/autogen-studio/usage.mdx, website/docs/tutorial/code-executors.ipynb
Changes in website/docs/autogen-studio/usage.mdx:
- Fix function name format: generate*images -> generate_images
Changes in website/docs/tutorial/code-executors.ipynb:
- Remove duplicate "the": "validate the safety of the the code" -> "validate the safety of the code"
- Remove duplicate "the": "get the the stock price gains" -> "get the stock price gains"
These changes improve documentation readability by fixing formatting inconsistencies and removing redundant words.
=> Fix typos and formatting in documentation

dotnet/src/AutoGen.Core/Extension/GroupChatExtension.cs, website/docs/ecosystem/azure_cosmos_db.mdx
Changes:
1. dotnet/src/AutoGen.Core/Extension/GroupChatExtension.cs
- // only keep the the messages
+ // only keep the messages
Reason: Removed duplicate word "the"
2. website/docs/ecosystem/azure_cosmos_db.mdx  
- Your can simplify
+ You can simplify
Reason: Fixed grammar error
These minor changes improve documentation clarity and code readability.
=> Fix typos and grammar

dotnet/website/articles/Roundrobin-chat.md
Changes:
1. dotnet/website/articles/Roundrobin-chat.md
- https://github.com/ag2ai/ag2/blob/dotnet/dotnet/sample/...
+ https://github.com/ag2ai/ag2/blob/main/dotnet/sample/...
Reason: Updated link path from 'dotnet' to 'main' branch to ensure correct example code reference
The change fixes a broken link in the documentation by pointing to the correct branch ('main' instead of 'dotnet'), ensuring users can access the example code properly.
=>  Fix incorrect link path in documentation

dotnet/test/AutoGen.Anthropic.Tests/AnthropicClientAgentTest.cs, dotnet/website/articles/getting-start.md
Changes:
1. dotnet/test/AutoGen.Anthropic.Tests/AnthropicClientAgentTest.cs:
- Old: weatherFunctionArgumets -> New: weatherFunctionArguments
Reason: Fixed spelling error in variable name for better code consistency
2. dotnet/website/articles/getting-start.md:
- Old: "donet" -> New: "dotnet" 
Reason: Corrected label name to match official .NET platform naming
Files modified:
- dotnet/test/AutoGen.Anthropic.Tests/AnthropicClientAgentTest.cs
- dotnet/website/articles/getting-start.md
=> Fix typos in variable names and documentation labels

.devcontainer/README.md, .devcontainer/dev/Dockerfile, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/general_issue.yml, README.md, TRANSPARENCY_FAQS.md, test/website/test_process_api_reference.py, test/website/test_process_notebooks.py, website/_blogs/2023-10-18-RetrieveChat/index.mdx, website/docs/Notebooks.mdx, website/docs/contributor-guide/docker.mdx, website/docs/ecosystem/agentops.mdx, website/docs/ecosystem/composio.mdx, website/docs/ecosystem/databricks.mdx, website/docs/ecosystem/llamaindex.mdx, website/docs/ecosystem/mem0.mdx, website/docs/ecosystem/memgpt.mdx, website/docs/ecosystem/microsoft-fabric.mdx, website/docs/ecosystem/ollama.mdx, website/docs/ecosystem/pgvector.mdx, website/docs/ecosystem/portkey.mdx, website/docs/ecosystem/promptflow.mdx, website/docs/installation/Docker.mdx, website/docs/installation/Installation.mdx, website/docs/installation/Optional-Dependencies.mdx, website/docs/topics/non-openai-models/cloud-bedrock.ipynb, website/docs/topics/non-openai-models/cloud-cerebras.ipynb, website/mint-json-template.json, website/mint-style.css
=> wording of the docs

dotnet/test/AutoGen.Mistral.Tests/MistralClientAgentTests.cs, dotnet/test/AutoGen.Ollama.Tests/OllamaAgentTests.cs
Changes in dotnet/test/AutoGen.Ollama.Tests/OllamaAgentTests.cs:
1. Method names:
- ItReturnValidMessageUsingLLavaAsync -> ItReturnsValidMessageUsingLLavaAsync
- ItReturnValidStreamingMessageUsingLLavaAsync -> ItReturnsValidStreamingMessageUsingLLavaAsync
2. Variable name:
- weatherFunctionArgumets -> weatherFunctionArguments
Reason: Fixed grammar for third-person singular verb form with "It" subject and corrected spelling of "Arguments". No functional changes, only improved readability and naming consistency.
=> Fix Grammar and Variable Name Typos

autogen/messages/agent_messages.py, test/messages/test_agent_messages.py
making TextMessage take a list[dict[str, str | dict[str, Any]]] as value because MultimodalConversableAgent was breaking while processing images.
making TextMessage take a list[dict[str, str | dict[str, Any]]] as value because MultimodalConversableAgent was breaking while processing images. Now with TextMessage taking dict with object value this should not breaking existing functionality of MultimodalConversableAgent
#558
=> making TextMessage take a list[dict[str, str | dict[str, Any]]] as value because MultimodalConversableAgent was breaking while processing images.

autogen/oai/completion.py, pyproject.toml, test/interop/langchain/test_langchain.py, test/interop/pydantic_ai/test_pydantic_ai.py, test/interop/pydantic_ai/test_pydantic_ai_tool.py, test/interop/test_interoperability.py
FLAML is currently included as a dependency, although no functionality is used. It requires many other packages such as PyTorch, making the distribution very heavy and likely to conflict with different packages.
This PR moves FLAML into optional dependencies until we fully remove dependency from it.
Closes #594, #597
=> FLAML moved to optional dependancies

website/_blogs/2024-12-20-RealtimeAgent/index.mdx, website/_blogs/2025-01-09-RealtimeAgent-over-WebRTC/index.mdx
This PR will update the RealtimeAgent blogposts to align the code in example to AG2 0.7.2 release
Closes #577
=> Update bloposts for RealtimeAgent

test/agentchat/realtime_agent/clients/test_gemini_realtime_client.py, test/agentchat/test_agent_logging.py, test/agentchat/test_assistant_agent.py, test/agentchat/test_async.py, test/agentchat/test_async_get_human_input.py, test/agentchat/test_cache_agent.py, test/agentchat/test_chats.py, test/agentchat/test_conversable_agent.py, test/agentchat/test_dependancy_injection.py, test/conftest.py, test/test_conftest.py
We often get a ReseourceExhausted exception in CI due to quota: 
https://github.com/ag2ai/ag2/actions/runs/12968968958/job/36172514039
This PR retries those tests after a 1 minute timeout. If they fail, after three retries it marks them as `xfail` (expected to fail).
Closes #655
=> Add retries and xfail on Gemini test failed on ResourceExhausted exception

website/docs/autogen-studio/faqs.mdx
I noticed a  issue in the last code block where the Gunicorn command for launching AutoGen Studio was incomplete. The command was missing the port specification, which is necessary for the server to run properly.
I’ve updated it to include the correct binding to `0.0.0.0:8081`. This should resolve the issue and allow the server to start as expected.  
Here’s the corrected command:  
```bash  
gunicorn -w $((2 * $(getconf _NPROCESSORS_ONLN) + 1)) --timeout 12600 -k uvicorn.workers.UvicornWorker autogenstudio.web.app:app --bind "0.0.0.0:8081"  
```
=> docs: Fix incomplete Gunicorn command Update faqs.mdx

autogen/agentchat/conversable_agent.py
The arg type is wrong. 
As internally, we have 
```
last_msg = messages[-1].get("content")
```
Fix the arg type
Tested with notebook/agentchat_nestedchat.ipynb
=> [Bug fix] Fix messages type for summary_from_nested_chats and its dependencies

test/conftest.py
=> Polish suppress decorator in tests

autogen/agentchat/conversable_agent.py, autogen/tools/__init__.py, autogen/tools/tool.py, notebook/agentchat_assistant_agent_stanalone.ipynb, notebook/agentchat_assistant_agent_standalone.ipynb, test/agentchat/test_assistant_agent.py
This PR will add the functionality to run ConversibleAgent and its subclasses as standalone agents which can write and execute code and independently call functions and tools
```python
x_assistant = AssistantAgent(name="x_assistant", llm_config=llm_config)
browser_use_tool = BrowserUseTool(
llm_config=llm_config,
)
hot_topic_res = x_assistant.run(
"Find out today's hot topic and an influencer who is talking about it on X using a web search",
tools=browser_use_tool,
)
print(hot_topic_res)
```
Closes #523
=> Make it easy to use single agent

autogen/agentchat/conversable_agent.py, notebook/agentchat_assistant_agent_standalone.ipynb, test/agentchat/test_assistant_agent.py
=> Add msg_to param to ConversableAgent.run

autogen/agentchat/contrib/agent_optimizer.py, autogen/agentchat/contrib/captainagent/agent_builder.py, autogen/agentchat/contrib/web_surfer.py, autogen/interop/interoperability.py
- **`agent_optimizer.py`**: Fixed `"formated_actions"` → `"formatted_actions"`.
- **`agent_builder.py`**: Corrected `"unexcepted"` → `"unexpected"` in a comment regarding SQLite versions.
- **`web_surfer.py`**: Fixed `"webapge"` → `"webpage"` in the function annotation.
- **`interoperability.py`**: Corrected `"formated"` → `"formatted"` in error messages related to interoperability types.
=> Fix typos in agent and interoperability modules

website/_blogs/2025-01-31-Websurfing-Tools/index.mdx
The link to a previous blog in the Browsing Capabilities blog needs an update based on new documentation.
N/A
=> [Docs] Correct blog link in Browsing Capabilities blog

website/docs/use-cases/community-gallery/community-gallery.mdx
I noticed a grammatical error in the instructions for adding application images. The sentence was missing the word "should" to make it grammatically correct.
I've updated it to:  
- The application image **should be** added to the `static/img/gallery` directory if the image is local. If the image is hosted online, just update the `image` property with the URL of the image.
=> docs: Fix grammar in image addition instructions

autogen/agentchat/realtime/experimental/realtime_swarm.py
To make the `question_message` that is sent to the `RealtimeAgent` configurable, we need to expose it as a param in `register_swarm` function, as we did for the `system_message`
Closes #819
=> Expose question_message param in register swarm

autogen/agentchat/conversable_agent.py
There's a bug with tools and swarm function registration: `Tool` does not support `__name__` but it has `_name`, so updated ConversableAgent._add_single_function to cater for this.
N/A
=> [Bug fix]: Fix tool registration from a Tool

autogen/agentchat/conversable_agent.py
Removes the hard coding of the code execution config on the internal agent created for ConversableAgent`s `run` method.
If code execution is required, the code execution config can be passed in through the `executor_kwargs` parameter on `run`.
By defaulting it, this was causing issues with new users trying the quick start examples.
N/A
=> Remove default code execution config from `run` executor agent

.github/workflows/core-test.yml, .github/workflows/test-with-optional-deps.yml
`build-check` is not passing and getting stuck because I used `paths` filter directly in `pull_request` trigger. This will not trigger `test` which is needed by `build-check` and `build-check` gets stuck.
The fix is to remove it and let `paths-filter` job handle it.
Closes #865
=> Fix stuck build check

website/docs/contributor-guide/file-bug-report.mdx, website/docs/contributor-guide/setup-development-environment.mdx, website/docs/ecosystem/agentops.mdx, website/docs/faq/FAQ.mdx, website/docs/home/quick-start.mdx
- Fixed incorrect article usage in `quick-start.mdx` ("in two-person comedy show" → "in a two-person comedy show").
- Corrected singular/plural inconsistency in `setup-development-environment.mdx` ("method" → "methods").
- Fixed incorrect verb form in `setup-development-environment.mdx` ("setup" → "set up").
- Updated outdated Twitter link in `agentops.mdx` to X.com.
- Corrected singular/plural mismatch in `FAQ.mdx` ("auto replie" → "auto replies").
=> fix(docs): Correct typos and minor wording issues in documentation

.github/workflows/contrib-graph-rag-tests.yml, .github/workflows/contrib-llm-test.yml, .github/workflows/contrib-test.yml, .github/workflows/core-llm-test.yml, .github/workflows/core-test.yml, .github/workflows/test-with-optional-deps.yml
Currently we run tests in main branch once everyday based on schedule. But this runs tests for the changes from previous day. If somehow the last commit has a failing test, then coverage gets affected. Even if the test is fixed, there is no way to retrigger the tests with latest changes on main. 
This PR tries to fix it by adding a manual way to trigger workflows with latest changes. This is also a step for eventually fixing the https://github.com/ag2ai/ag2/issues/890.
=> Add a way to manually trigger workflow when needed

autogen/agentchat/contrib/rag/document_utils.py, test/agentchat/contrib/rag/test_document_utils.py
The unit tests are failing. Right now some are still failing from dev docker container because of Selenium exception.
This PR fix the tests that they are tested successfully from local as following,
```
pytest test/agentchat/contrib/rag/test_document_utils.py
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0
rootdir: /Users/yzhai/workspace/ag2ai/ag2
configfile: pyproject.toml
plugins: cov-6.0.0, anyio-3.5.0, devtools-0.12.2
collected 23 items                                                                                                                                           
...
-- Docs: …
```
=> Fix document utils tests

.secrets.baseline, autogen/agentchat/contrib/swarm_agent.py, test/agentchat/contrib/test_swarm.py
This will add a custom fialed serializer for the agent field in the SwarmReslut which will enable the SwarmResult to serialize the ConversableAgent class using agent.name property
Closes #943
=> Add custom field serializer for agent in SwarmResult

.secrets.baseline, autogen/oai/gemini.py, test/agentchat/test_conversable_agent.py, test/oai/test_gemini.py
- `google.genai` does not support `anyOf` parameters so currently nothing can be done about it - [discussion](https://discuss.ai.google.dev/t/oneof-in-response-schema/55926/23)
- `vertexai` supports `anyOf` parameters but it doesn't work with the following schema: 
`"anyOf": [{"type": "string"}, {"type": "null"}]`
this schema needs to be converted to:
`"anyOf": [{"type": "string"}, {"nullable": True}]`
Closes #611
=> Fix gemini client with anyof  nullable function parameters

.github/workflows/contrib-test.yml, .github/workflows/test-with-optional-deps.yml, autogen/agentchat/contrib/vectordb/couchbase.py, test/agentchat/contrib/vectordb/test_couchbase.py
Couchbase is not passing documentation build or tests workflows.
Identified that it is using non-3.9 compatible features, like `|`.
Note: Couchbase test for retrieval is failing. It is being ignored for now so that CI can pass and not hold up other PRs. Additionally, have removed from `test-with-optional-deps.yml` as it is failing.
Issue #981 has been raised to fix these issues and allow this to be merged to prevent other PRs from being blocked.
N/A
=> Couchbase fixes for documentation and tests

website/docs/use-cases/reference-agents/communication-agents.mdx
Fix warning format in Communication Agents documentation, fix incorrect link, add some API reference links.
N/A
=> [Docs] Fix warning, incorrect link, and add API links.

autogen/agentchat/conversable_agent.py, test/agentchat/test_conversable_agent.py
We should be able to use `agent.run(...` multiple times without losing chat history
e.g.
```python
assistant = AssistantAgent(
name="Assistant",
llm_config=llm_config,
)
chat_result = assistant.run(
message="what is two plus two?",
max_turns=1,
user_input=False,
)
```
```console
user (to Assistant):
what is two plus two?
--------------------------------------------------------------------------------
Assistant (to user):
Two plus two equals four.
--------------------------------------------------------------------------------
```
And then send another message (without losing chat history):
```python
chat_result = assistant.run(
message="What was my last question?",
max_turns=1,
user_input=False,
)
```
```console
user (to Assistant):
What was my last question? …
```
=> Preserve chat history when using 'agent.run'

autogen/agentchat/conversable_agent.py
The hook processing order on `generate_reply` and `a_generate_reply` is different.
Correcting `a_generate_reply` to be:
- update_agent_state
- process_last_received_message
- process_all_messages_before_reply
N/A
=> Correct hook processing order on ConversableAgent.a_generate_reply

autogen/agentchat/conversable_agent.py
=> Fix check_termination_and_human_reply() when called with empty list as messages

autogen/oai/gemini.py, test/agentchat/contrib/test_swarm.py
Fixes issues with tests failing:
- Swarm tests failed because the removal of transfer messages is on by default now, updated tests to not remove the transfer messages.
- Gemini failed because it wasn't handling asynchronous use of the client which the genai.Client class did not like as we use `run_in_executor`. Tested with direct API and with vertex AI and appears okay now.
Closes #1121
Closes #1122
=> Swarm and Google Gemini client test fixes

.secrets.baseline, autogen/agentchat/contrib/swarm_agent.py, test/agentchat/contrib/test_swarm.py
The previous constructor of SwarmResult converts AfterWorkOptions to a string. This causes exceptions when a function sets an AfterWorkOption as the next agent.
The current constructor of SwarmResults converts AfterworkOption to `str`. This causes exceptions when trying to select the next agent, because the str is compared against the list of all agents, but the agent doesn't exist.
=> Solves issue with SwarmResult.agent AfterWorkOption -> str

autogen/agentchat/conversable_agent.py, test/agentchat/test_conversable_agent.py
In ConversableAgent the update_tool_signature function allows a string or dictionary to be passed in but if set for removal it only evaluates it against the dictionary value.
This was causing the swarm to fail because tools would not be removed for the conditional hand offs.
N/A
=> Enable tool removal by name

test/agentchat/contrib/test_gpt_assistant.py
With 0.7.6 removing openai package, the GPT Assistant tests were failing as they assume openai is installed.
N/A
=> GPT Assistant tests - cater for openai dependency

autogen/oai/client.py, pyproject.toml
Further updates now that openai is an optional dependency (based on tests failing):
OpenAI exception handling and httpx dependency
N/A
=> OpenAI exception handling and httpx dependency

autogen/agentchat/utils.py, test/agentchat/test_utils.py, website/docs/user-guide/advanced-concepts/swarm/deep-dive.mdx
A useful mechanism in ContextExpression to check if lists have items or not, e.g.:
```
OnContextCondition(
target=my_agent,
condition=ContextExpression("len(${orders}) > 0")
)
```
N/A
=> ContextExpression support for len for collections

scripts/docs_build.sh
I’ve added a check to ensure the script is executed directly and not sourced. The check now uses `realpath` to verify that the script's path is absolute, improving accuracy. This replaces the old `if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then`, making the execution condition more reliable and precise.
These changes improve the script’s reliability by ensuring it’s only executed directly and not sourced. The previous method for checking script execution was less precise, and this update provides a more accurate solution by using `realpath`.
=> fix: fix script execution check for direct run

website/user-guide/captainagent/configurations.mdx
I noticed a issue in the documentation for the `group_chat_config` section. The default value for the `max_round` parameter was incorrectly listed as `10`, but it should actually be `15` according to the example configuration provided earlier.
Here’s the corrected version:
```
Specifies the maximum number of rounds in a group chat session. Defaults to `15`.
```
This update should clarify the correct default value.
---
The default value for `max_round` in the `group_chat_config` section was listed incorrectly as `10`. The correct default value, according to the example configuration, is `15`. This change ensures the documentation is accurate and consistent.
=> chore: fix default value for `max_round` in `group_chat_config` section

autogen/oai/oai_models/chat_completion_message.py, autogen/oai/openai_utils.py, pyproject.toml, test/agentchat/contrib/test_gpt_assistant.py
Fix use of vector_stores from the OpenAI package, no longer in beta.
Update OpenAI dependency to minimum of 1.66.2
Closes #1319
=> Updated support for OpenAI package 1.66.2

website/docs/user-guide/models/google-gemini.mdx
Gemini docs were missing the guidance to use GOOGLE_GEMINI_API_KEY instead of `api_key`.
N/A
=> Add guidance on using GOOGLE_GEMINI_API_KEY

autogen/agentchat/conversable_agent.py, autogen/agentchat/groupchat.py, autogen/messages/agent_messages.py, test/messages/test_agent_messages.py
It's not always clear why a workflow ends, so introducing termination messages assists in providing clear reasons why a conversation is terminating.
**Note:** There is no way to turn these specific messages on or off so they will be pushed to the iostream like other messages. They are, however, a new type of message, `TerminationMessage`.
Examples of termination messages, these appear upon termination:
Blank reply:
```
human (to gcm):
And more blank!
--------------------------------------------------------------------------------
Next speaker: blank_agent
>>>>>>>> TERMINATING: No reply generated.
```
Maximum turns reached:
```
my_agent (to user):
If you have any more questions or need assistance, feel free to ask! G'DAY!
--------------------------------------------------------------------- …
```
=> Termination messages

website/docs/user-guide/advanced-concepts/code-execution.mdx
As per [Discord issue](https://discord.com/channels/1153072414184452236/1349181422832980008/1349181422832980008), the code execution sample uses '''python instead of ```python. This means that running it as is won't work.
The documentation doesn't build successfully if I change it, so have changed the string:
```
message_with_code_block = """This is a message with code block.
The code block is below:
``""" + """`python
import numpy as np
import matplotlib.pyplot as plt
x = np.random.randint(0, 100, 100)
y = np.random.randint(0, 100, 100)
plt.scatter(x, y)
plt.savefig('scatter.png')
print('Scatter plot saved to scatter.png')
``""" + """`
This is the end of the message.
"""
```
N/A
=> Correct code execution document text

autogen/agentchat/contrib/swarm_agent.py, autogen/agentchat/conversable_agent.py, autogen/tools/dependency_injection.py
Two issues:
1. Swarms register and update functions throughout their lifecycle and warning messages about overriding functions/tools were being output. This provides the ability to suppress those warnings.
2. Dependency Injection included a function that had a parameter starting with an underscore and this was causing Pydantic warning messages to show:
`/app/.local/lib/python3.9/site-packages/pydantic/main.py:1630: RuntimeWarning: fields may not start with an underscore, ignoring "_x"
warnings.warn(f'fields may not start with an underscore, ignoring "{f_name}"', RuntimeWarning)`
Closes #1333
=> Suppress warnings

autogen/agentchat/contrib/capabilities/generate_images.py, autogen/agentchat/realtime/experimental/clients/oai/base_client.py, autogen/coding/jupyter/import_utils.py, autogen/import_utils.py, autogen/oai/client.py, test/test_import_utils.py
Also, can we check the openai version in the import_openai attempt? There's an old openai version available which passes that import attempt but should be considered as a failure of import instead [ref](https://discord.com/channels/1153072414184452236/1248044812956074075/1349149229733515357).
Closes #1330
=> Add package version to import utils

autogen/tools/function_utils.py
When using Pydantic version < v2.10.2, we get this error:
```
from pydantic._internal._typing_extra import try_eval_type  # type: ignore[attr-defined]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'try_eval_type' from 'pydantic._internal._typing_extra' (.../site-packages/pydantic/_internal/_typing_extra.py). Did you mean: '_eval_type'?
```
The reason is internal change in a way forward references are being evaluated.
This PR uses different functions for evaluating forwarded references, depending on the version of Pydantic installed.
Closes #1316
=> Fix pydantic import issue for version <2.10.2

autogen/agentchat/groupchat.py, autogen/messages/agent_messages.py, test/messages/test_agent_messages.py
As we sometimes run chats within chats, the terminating messages may look like the main chat is terminating. To assist, we are adding the ID to help distinguish if you see multiple termination messages.
It would also be good to have a message when starting a chat that has the ID so that it can be associated with the termination. Not in this PR.
N/A
=> Add UUID to terminating messages

autogen/agentchat/contrib/rag/llamaindex_query_engine.py, pyproject.toml
Type checks are failing for LlamaIndexQueryEngine:
```
autogen/agentchat/contrib/rag/llamaindex_query_engine.py:174: error: Need type annotation for "loaded_documents" (hint: "loaded_documents: list[<type>] = ...")  [var-annotated]
autogen/agentchat/contrib/rag/llamaindex_query_engine.py:179: error: "BaseReader" not callable  [operator]
autogen/agentchat/contrib/rag/llamaindex_query_engine.py:186: error: "BaseReader" not callable  [operator]
autogen/agentchat/contrib/rag/llamaindex_query_engine.py:186: note: Error code "operator" not covered by "type: ignore" comment
```
N/A
=> Type fixes for LlamaIndexQueryEngine

test/agentchat/contrib/rag/test_llamaindex_query_engine.py
=> Import optional dependencies inside with optional_import_block

autogen/oai/openai_utils.py
`get_key` in `openai_utils.py` was crashing when the llm config contained a HttpUrl parameter.
N/A
=> Update get_key in openai_utils to fix serialisation issue

autogen/agentchat/conversable_agent.py, test/agentchat/test_conversable_agent.py
=> bug fix for max_consecutive_auto_reply

autogen/agentchat/contrib/captainagent/agent_builder.py, autogen/agentchat/contrib/captainagent/captainagent.py, autogen/llm_config.py, autogen/oai/client.py
=> Fix exception in CaptainAgent when using LLMConfig

autogen/oai/gemini.py, autogen/oai/gemini_types.py, pyproject.toml, test/oai/test_gemini_types.py
=> Add copy of Gemini ToolConfig in local

notebook/tools_youtube_search.ipynb, website/mint-json-template.json.jinja
Add YouTube tool notebook metadata and Documentation page link
N/A
=> YouTube tool notebook metadata and documentation page linking

website/docs/user-guide/basic-concepts/conversable-agent.mdx
Improved the ConversableAgent documentation to enhance readability and accessibility:
- Refined explanations for clarity
- Hyperlinked the first reference to [ConversableAgent] to the API docs
- Added a <Tip> block with links to real-world examples
- Passed pre-commit checks successfully
Closes #1507
=> Clean up ConversableAgent doc: improved clarity, added example links

autogen/agentchat/contrib/llamaindex_conversable_agent.py
The original check using `description.isspace()` fails to catch empty strings (`""`), allowing invalid inputs to pass through. This fix ensures that both `None`, empty strings, and strings with only whitespace are properly handled by using `not description or description.strip() == ""`.
=> chore: fix validation logic for empty descriptions

README.md
The link to basic concepts is broken. This PR fixes it by pointing to the basic concepts section in 0.8.5 docs.
Closes #1547
=> Fixes the URL to Basic concepts in README.md

website/mkdocs/docs/stylesheets/extra.css, website/mkdocs/overrides/home.html
#1605 fixed accessing the menu on the Docs home page on mobile, but added these gaps to the desktop breakpoint.
The sidebar divs aren't needed on the docs home page on desktop (so they should be hidden) but are necessary for viewing the menu on mobile. So I updated the CSS to hide these only on the Desktop breakpoint.
None. Just a quick bug fix.
=> [Docs] Home Page bug fix on desktop breakpoint

website/mkdocs/overrides/home.html
As per feedback from @qingyun-wu, I'm updating a heading on the docs home page from "The End-to-End Platform for Multi-Agent Automation" to "The Open-Source Operating System for Agentic AI". The word 'automation' is a bit restricted.
None. Just a quick wording update
=> [Docs] Wording tweak on home page

README.md, announcements.md
Several documentation links in `README.md` and `announcements.md` were outdated and returning 404 errors. I updated them to point to the correct current locations in our documentation.
=> chore: fixed dead links

autogen/agentchat/contrib/graph_rag/falkor_graph_query_engine.py, autogen/agentchat/contrib/swarm_agent.py
I am doing one poc with a_run_swarm. I am just replicating the context router example using a_run_swarm. it didn't get transitioned properly. I got an error saying,
`AttributeError: 'ConversableAgent' object has no attribute '_swarm_manager'`
Closes #1603 
I haven't done anything in checks. But, I am thinking it's a minor fix, so.
=> fix: register_handoff is not working as expected in a_run_swarm 

autogen/oai/client.py
`print(f"{params=}")` unconditionally sends internal request parameters to **stdout** for the `o1` / `o1‑mini` code path.  
This risks leaking sensitive prompt data, and is inconsistent with other models.
Switching to `logger.debug(...)` (or removing the call) keeps stdout clean while still allowing developers to view the same details via standard logging configuration.
Closes #1624
=> Fix: stop printing request params to stdout for `o1` /` o1‑mini`; switch to `logger.debug`

autogen/agentchat/contrib/rag/llamaindex_query_engine.py
Removes the redundant `((...))` brackets in the docstring to maintain correct formatting
=> docs: fix extra parentheses in docstring

autogen/oai/client.py, test/oai/test_client.py
=> Disable default cache when both cache and cache_seed are not set

website/docs/user-guide/basic-concepts/tools/basics.mdx, website/docs/user-guide/basic-concepts/tools/index.mdx
I noticed that the 'Tools' page showed 'Index' in the header, which was not ideal. This work fixes that.
Note: The tools page is organized a bit differently as most sections don't have a top level page, but instead, just load the first page of the section when you click on them. That being said, I think that should be part of a larger reorg of documentation. This was just a small PR to fix the title.
None
=> [Docs] Small fix to header on Tools page

autogen/tools/function_utils.py, test/tools/test_function_utils.py
When a function is converted to a tool it can cause a crash if it has a parameter that is a `list`.
This PR is to fix this issue.
Raised as an issue on Discord, [message link](https://discord.com/channels/1153072414184452236/1153072414184452241/1362173999907602683).
Note: I've tested if this was an issue for response formats that had a parameter as a `list` and it isn't.
N/A
=> Allow lists to be a parameter in a function for a tool

website/snippets/python-examples/structured_output.mdx
The example for Structured Output didn't have the correct `max_turns` set. Also have set `user_input` to `True` incase a developer changes `max_turns` to more than 1.
N/A
=> Fix Structured Output documentation example

autogen/oai/anthropic.py, website/docs/user-guide/models/anthropic.mdx
Support for "thinking" section in LLM Config to allow using Claude 3.7 [Extended Thinking](https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking?q=extended_thinking#pricing-and-token-usage-for-extended-thinking).
```
llm_config = {
"config_list": [
{
"model": "claude-3-7-sonnet-20250219",
"api_key": "your key",
"api_type": "anthropic",
"max_tokens": 8192, # ovveride the default value of 4096, max tokens must be greater than thinking budget
"timeout": 600, # for larger thinking budgets, increase the timeout OR enable streaming
"thinking": {"type": "enabled", "budget_tokens": 2048},
}
],
"cache_seed": None,
}
agent = ConversableAgent(
name="test",
llm_config=llm_config,
)
response = agent.generate_reply(
messages=[{"role": "user", "content": "Please provide a comparison of …
```
=> Anthropic Extended Thinking support

autogen/oai/oai_models/chat_completion.py, test/oai/test_anthropic.py, test/tools/experimental/tavily/test_tavily.py
OpenAI's ChatCompletion `service_tier` parameter was updated, this aligns with that. As well as fixes some test failures for TavilySearchTool and Anthropic.
N/A
=> OpenAI ChatCompletion alignment, Tavily test fix, Anthropic test fix

autogen/tools/experimental/google/drive/drive_functions.py, autogen/tools/experimental/google/drive/toolkit.py
The current `download_file_from_drive` tool in the GoogleDriveToolkit will download a file to the configured download directory but you can't provide an option to download it to a sub folder within that directory. This PR adds that ability.
N/A
=> Google Drive tools - Add ability to download to a subfolder

website/docs/contributor-guide/how-ag2-works/initiate-chat.mdx
Fixes a minor typo and improves clarity in the Chat workflow documentation example. Also corrects a code snippet to ensure the recipient agent is correctly set in initiate_chat.
Closes #1677 
- [o] I've included any doc changes needed for https://docs.ag2.ai/. See https://docs.ag2.ai/docs/contributor-guide/documentation to build and test documentation locally.
- [o] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [o] I've made sure all auto checks have passed.
This PR includes:
- Correction to the initiate_chat example (recipient=agent_a → recipient=agent_b)
=> Typo in agent example: initiate_chat has wrong recipient

notebook/agentchat_swarm.ipynb
Emmanual A on Discord noted that the Swarm notebook example is not updating the context variables. Looking at the notebook, the `context_variables` parameter is missing from the `initiate_swarm_chat`:
https://docs.ag2.ai/0.9dev/docs/use-cases/notebooks/notebooks/agentchat_swarm/?h=swarm+orchestrat#run-the-code
This PR updates that (and increases `max_rounds` as 20 is too short)
N/A
=> Fix missing context_variables in Swarm notebook

autogen/agentchat/group/group_utils.py, autogen/agentchat/group/patterns/pattern.py
The new group chat functionality was not checking if the LLM config was required if the group had an after work target of GroupManagerTarget. This fixes that.
N/A
=> Check group-level afterwork when validating group manager's LLM Config

autogen/agentchat/conversable_agent.py
Tools can be duplicated on ConversableAgent's `_tools` parameter, this fixes that.
This was occurring when running an agent's run multiple times inside a loop, it kept adding the tools over and over to the agent's `_tools` parameter. 
N/A
=> Don't add existing tool to _tools on ConversableAgent

autogen/oai/gemini.py
Recitation finish reasons can occur if the Gemini model starts returning content that is in its training data, particularly what it thinks is copyrighted material:
https://github.com/google/generative-ai-docs/issues/257#issuecomment-1939213935
This PR will gracefully pick up that finish reason and return the text "Unsuccessful Finish Reason: RECITATION" together with a finish reason value of "content_filter".
CC @rjambrecic, @kumaranvpl, @davorrunje 
N/A
=> Handle Recitation result gracefully in Gemini client

notebook/agentchat_tabular_data_rag_workflow.ipynb, website/user-guide/captainagent/tool_library.mdx
This PR fixes two minor typos:
1. Corrects "finanical" to "financial" in the notebook example text
2. Fixes "reove" to "remove" in the tool library documentation comment
=> Fix typos: "finanical" -> "financial" and "reove" -> "remove"

website/docs/_blogs/2025-04-16-Reasoning/index.mdx
In reading through The Myth of Reasoning blog post (https://docs.ag2.ai/latest/docs/_blogs/2025-04-16-Reasoning/), I noticed a few small typos. Created this small PR to fix them.
n/a
=> Fixing typos in Reasoning Blog post

test/interop/crewai/test_crewai.py
Fix the tool description for the CrewAI file read tool as it has changed and it's failing tests.
N/A
=> Fix the tool description in CrewAI file read tool test

.github/PULL_REQUEST_TEMPLATE.md
Replaced `https://docs.ag2.ai/docs/contributor-guide/documentation`
with `https://docs.ag2.ai/latest/docs/contributor-guide/documentation/`
— directs straight to the working page, eliminating the redirect.
=> docs: update contributor guide URL

autogen/oai/client.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Fix logger warnings

announcements.md
This PR fixes a broken link in announcements.md pointing to the installation documentation.
The link https://docs.ag2.ai/docs/installation/Installation (404) has been updated to the current working URL: https://docs.ag2.ai/latest/docs/user-guide/basic-concepts/installing-ag2/
This ensures users are directed to the proper installation instructions for AG2.
=> Fix broken installation documentation link

autogen/oai/client.py
The changes in this PR address the issue: https://github.com/ag2ai/ag2/issues/1778
At this moment we are unable to use the "gpt-4.1" model with AG2 as the _configure_azure_openai function replaces the dots within the deployment name and converts it to "gpt-41" which does not work.
https://github.com/ag2ai/ag2/issues/1778
- [ ✔️] I've made sure all auto checks have passed.
=> improved azure openai deployment name parsing (fixes the "gpt-4.1" turning to "gpt-41")

autogen/interop/litellm/litellm_config_factory.py, test/interop/litellm/test_litellm_config_factory.py
When using AG2's WebSurferAgent with crawl4ai >=0.5, the following error occurs:
```
Error: Setting 'provider' is deprecated. Instead, use llm_config=LLMConfig(provider="...")
```
https://github.com/ag2ai/ag2/issues/1776
=> Resolves deprecated provider error when using WebSurferAgent 

pyproject.toml
Hi! I'm here because I'm working on the google a2a-samples repo here: https://github.com/google-a2a/a2a-samples/tree/main/samples/python/agents/ag2 
Ag2 is pinning the max version of MCP which is an issue when trying to work alongside other frameworks which require newer versions of MCP. I believe that the issue you encountered for the original reason for pinning MCP should be resolved by now, so it's no longer necessary. Thanks!
Found while working on https://github.com/mozilla-ai/any-agent/issues/410
=> feat: unpin mcp version

autogen/agentchat/group/group_utils.py, autogen/agentchat/group/patterns/pattern.py, test/agentchat/group/test_group_utils.py
In the new group chat the context variables do not get associated with the user_agent of the pattern. This fixes that.
=> Add context variables to the user proxy agent in group chat

autogen/agentchat/group/group_utils.py, autogen/agentchat/group/handoffs.py, autogen/agentchat/group/on_context_condition.py, test/agentchat/group/test_group_utils.py, test/agentchat/group/test_handoffs.py, test/agentchat/group/test_on_context_condition.py
After works can now be a set of conditional OnContextCondition. Made `condition` optional on OnContextCondition so an OnContextCondition can be triggered without a condition (defaults to True) to support the existing set_after_work in setting a condition for transfer. 
N/A
=> Change After Works on handoffs to a list of OnContextConditions

pyproject.toml
Google's `google-genai` was failing with version 1.18.0 as per #1843. Version 1.20 fixed it.
Closes #1843
=> Update google-genai version in pyproject.toml

.devcontainer/python-3.10/devcontainer.json, scripts/devcontainer/templates/devcontainer.json.jinja
Modified File:
.devcontainer/python-3.10/devcontainer.json
Changes:
Removed trailing commas after:
"AZURE_API_VERSION" in secrets
"AZURE_API_VERSION" in remoteEnv
Reason:
Trailing commas are invalid in JSON and can cause parsing errors. This fix ensures proper JSON formatting and prevents runtime issues in devcontainer setups.
=> Fix trailing commas in devcontainer.json

website/mint-json-template.json.jinja
for guardrail documentation, I can't find it from side bar. 
I built it from local. 
http://localhost:8000/docs/user-guide/advanced-concepts/orchestration/group-chat/introduction/
I can search and find the page
http://localhost:8000/docs/user-guide/advanced-concepts/orchestration/group-chat/guardrails/
I did './scripts/docs_build_mkdocs.sh' and './scripts/docs_serve_mkdocs.sh'
=> [Bug fix] Add guardrails page to the sidebar

autogen/llm_config.py, autogen/oai/client.py, test/oai/test_client.py, test/test_llm_config.py
This PR introduces a `routing_method` parameter to `LLMConfig` and `OpenAIWrapper`, allowing users to define the strategy for selecting language model configurations from a list.
Supported routing methods:
- `fixed_order`: (Default) Always tries configurations in the order they are defined in the `config_list`.
- `round_robin`: Rotates the starting configuration in the `config_list` for each API call, continuing through the list sequentially if earlier attempts fail.
- smarter routing can be added in future. @DujianDing
The `routing_method` is a wrapper-level parameter, determining how the entire list of configurations is traversed. It defaults to `None` in `LLMConfig` and is handled as `fixed_order` by `OpenAIWrapper` if not specified or `None`.
Individual configurations within the …
=> feat: Add configurable routing method to LLMConfig and OpenAIWrapper

autogen/tools/tool.py, test/mcp/test_mcp.py
The goal of this PR is to resolve https://github.com/ag2ai/ag2/issues/1947 by registering MCP tools in a similar way to resources, rather than skipping them.
Closes https://github.com/ag2ai/ag2/issues/1947
=> Bugfix: Register MCP Tools Like MCP Resources

autogen/oai/gemini.py, test/oai/test_gemini.py
Add support for the use of the `seed` value in the base `LLMConfig` in the Gemini client.
N/A
=> Add support for seed parameter for Gemini client

.github/workflows/contrib-graph-rag-tests.yml, .github/workflows/contrib-llm-test.yml, .github/workflows/core-llm-test.yml, .github/workflows/integration-test.yml
Four workflows are running, that require review, on a daily basis. It's not necessary to run these so frequently and this PR changes the schedule for these workflows to weekly (Sunday midnight UTC).
N/A
=> Repo: Adjust schedule for workflows requiring review

autogen/fast_depends/_compat.py, pyproject.toml
Mypy couldn't resolve anyio imports, so we should type exception groups using sys-only
Fixes #1978
=> lint: fix ExceptionGroup imports

README.md, website/docs/home/quickstart.mdx
Just a little fix of main branch repository badges representation. In the main branch "downloads" badge even doesn't work.
You can take a look at current view in the branch: https://github.com/ag2ai/ag2/tree/docs/fix-badges
=> docs: polish badges

website/docs/contributor-guide/building/creating-a-tool.mdx, website/docs/contributor-guide/building/creating-an-agent.mdx, website/docs/contributor-guide/contributing.mdx, website/docs/contributor-guide/file-bug-report.mdx, website/docs/contributor-guide/how-ag2-works/generate-reply.mdx, website/docs/contributor-guide/how-ag2-works/initiate-chat.mdx, website/docs/contributor-guide/maintainer.mdx
Fix list rendering in contribution guide part of docs:
- Lists need empty string if they used right after plain text (not special blocks like heading / tab / code example)
- Nested lists need additional indent (4 spaces)
| Before | After |
|---|---|
|<img width="814" height="887" alt="image" src="https://github.com/user-attachments/assets/40f7440c-d155-4e53-95a5-7ce6e26eb36f" /> | <img width="814" height="887" alt="image" src="https://github.com/user-attachments/assets/aa9e6c7e-4d41-425b-aa71-187d04c9c4bd" /> |
| <img width="803" height="272" alt="image" src="https://github.com/user-attachments/assets/fc98f7ed-5456-4983-a0a1-2e2a4da92442" /> | <img width="803" height="272" alt="image" src="https://github.com/user-attachments/assets/9a7ab7bc-0af4-4b03-bb20-2de224dd35f9" /> |
Relevant to …
=> docs: fix list rendering in contribution guide part of docs

autogen/agentchat/groupchat.py
I am not sure about case, where messages has no content.
But we can not be sure about cases we didn't see. So, supporting such cases makes the library much sustainable
Also such changes are correct from typing side.
Fixes #1891
=> fix: proccess messages without content

autogen/mcp/mcp_proxy/mcp_proxy.py
**Why are these changes needed?**
The FastMCP class in newer versions no longer accepts a title keyword argument.
This was causing a TypeError in MCPProxy.get_mcp when trying to initialize FastMCP.
This change updates the call to use name= instead, which matches the current constructor signature,
allowing MCP clients to initialize without error.
**Related issue number**
Closes #<issue-number-if-any>
(No existing issue found — discovered during local testing.)
**Checks**
I've reviewed whether any doc changes are needed for https://docs.ag2.ai/. (No doc changes required.)
=> mcp_proxy: FastMCP init uses name= (not title=)

autogen/oai/cerebras.py
Added support for reasoning_effort param for Cerebras API provider - before the change supplying the param lead to LLM Config validation issues. With the change I got qwen-3-235b-a22b-thinking-2507 running.
Beside the effort fixed a typo and a few inconsistencies (e.g. using float as default val for temp) 
- [N/A ] I've included any doc changes needed for https://docs.ag2.ai/. See https://docs.ag2.ai/latest/docs/contributor-guide/documentation/ to build and test documentation locally.
- [N/A ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [N/A ] I've made sure all auto checks have passed.
=> Cerebras, support for reasoning_effort, minor typos

autogen/llm_config/entry.py, test/oai/test_cerebras.py, test/oai/test_client.py
Remove LLMConfig `temperature` and `top_p` options constraint.
It was a good idea to validate user-provided options before passing them to the outer LLM client, but I don't think such validation should be too strict. We can simply validate the option types and pass them on to the external config as they are.
I propose this change for one reason: the external provider could change their API, option restrictions, and other things. By making our validation a replica of these constraints, we are heavily dependent on the external API that we cannot control. Therefore, if the LLM provider changes their options, our constraints may no longer be relevant.
This is why we provide users with the ability to pass additional options to config, and this is why we should not validate user input too …
=> fix: remove temperature & top_p restriction

.github/workflows/contrib-llm-test.yml
In the Contributor LLM test put OAI_CONFIG_LIST secret to disk
AgentBuilder tests failing due to OAI_CONFIG_LIST file missing.
N/A
=> [Fix] OAI_CONFIG_LIST for tests
